/**
 * LangGraph 各阶段 JS/Python 对比代码示例
 * 存放所有阶段的代码示例，供各 Stage 组件引用
 */

export const stage4JsCode = [
  "import { StateGraph, Annotation, START, END, Command } from '@langchain/langgraph'",
  "import { ChatOpenAI } from '@langchain/openai'",
  '',
  '// ============================================================',
  '// 方式一：Command 命令式路由（节点内决策）',
  '// ============================================================',
  '',
  '// 1. 定义状态',
  'const AnalyzerState = Annotation.Root({',
  '  text: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => ''",
  '  }),',
  '  priority: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => 'normal'",
  '  }),',
  '  handled: Annotation<boolean>({',
  '    reducer: (_, right) => right,',
  '    default: () => false',
  '  }),',
  '  handlerNote: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => ''",
  '  }),',
  '})',
  '',
  '// 2. analyzer 节点：LLM 分析 + Command 动态路由',
  'const analyzerNode = async (state) => {',
  '  const { text } = state',
  '',
  '  // ⚡ 用 LLM 分析消息分类',
  "  const prompt = `请分析以下消息的分类，只返回一个单词：",
  "  - 紧急/故障/宕机 → 返回 'urgent'",
  "  - 投诉/不满/抱怨 → 返回 'complaint'",
  "  - 结束/终止/再见 → 返回 'end'",
  "  - 其他 → 返回 'normal'",
  '',
  "  消息：${text}",
  '',
  '  分类结果：`',
  '',
  '  const response = await llm.invoke([new HumanMessage(prompt)])',
  "  const category = response.content.trim().toLowerCase()",
  '',
  '  // 🔀 在节点内部根据 LLM 分类结果用 Command 动态路由',
  "  if (category === 'urgent') {",
  '    return new Command({',
  "      goto: 'priorityHandler',",
  "      update: { priority: 'high', handled: true },",
  '    })',
  "  } else if (category === 'complaint') {",
  '    return new Command({',
  "      goto: 'escalationHandler',",
  "      update: { priority: 'critical', handled: true },",
  '    })',
  "  } else if (category === 'end') {",
  '    return new Command({',
  '      goto: END,',
  '      update: { handled: true },',
  '    })',
  '  }',
  '',
  '  // ➡️ 普通消息 → 不返回 Command，走默认边',
  "  return { priority: 'normal', handled: false }",
  '}',
  '',
  '// 3. 各处理节点',
  "const priorityHandler = (state) => ({",
  "  handlerNote: `[优先处理] 已紧急响应: ${state.text.substring(0, 50)}`,",
  '})',
  '',
  "const escalationHandler = (state) => ({",
  "  handlerNote: `[升级处理] 已升级投诉: ${state.text.substring(0, 50)}`,",
  '})',
  '',
  "const normalHandler = (state) => ({",
  "  handlerNote: `[普通处理] 已记录: ${state.text.substring(0, 50)}`,",
  '  handled: true,',
  '})',
  '',
  '// 4. 构建图（注意：使用 Command 的节点需要声明 ends 数组）',
  'const graph = new StateGraph(AnalyzerState)',
  "  .addNode('analyzer', analyzerNode, {",
  "    ends: ['priorityHandler', 'escalationHandler', 'normalHandler', END]",
  '  })',
  "  .addNode('priorityHandler', priorityHandler)",
  "  .addNode('escalationHandler', escalationHandler)",
  "  .addNode('normalHandler', normalHandler)",
  "  .addEdge(START, 'analyzer')",
  "  .addEdge('priorityHandler', END)",
  "  .addEdge('escalationHandler', END)",
  "  .addEdge('normalHandler', END)",
  '',
  '// 5. 编译并执行',
  'const app = graph.compile()',
  "const result = await app.invoke({ text: '紧急！服务器宕机了' })",
  '',
  '',
  '// ============================================================',
  '// 方式二：条件边 声明式路由（对比）',
  '// ============================================================',
  '',
  '// 条件边版本：同样使用 LLM 分类，仅路由方式不同',
  '// 节点只负责设置状态字段，路由逻辑在边层面的 router 函数中',
  'const analyzerNodeV2 = async (state) => {',
  '  const { text } = state',
  '',
  '  // ⚡ 用 LLM 分析消息分类（与 Command 模式相同的 prompt）',
  "  const prompt = `请分析以下消息的分类，只返回一个单词：",
  "  - 紧急/故障/宕机 → 返回 'urgent'",
  "  - 投诉/不满/抱怨 → 返回 'complaint'",
  "  - 结束/终止/再见 → 返回 'end'",
  "  - 其他 → 返回 'normal'",
  '',
  '  消息：${text}',
  '',
  '  分类结果：`',
  '',
  '  const response = await llm.invoke([new HumanMessage(prompt)])',
  "  const category = response.content.trim().toLowerCase()",
  '',
  '  // 根据 LLM 分类结果设置状态字段（不直接路由）',
  "  if (category === 'urgent') return { priority: 'high' }",
  "  if (category === 'complaint') return { priority: 'critical' }",
  "  if (category === 'end') return { shouldEnd: true }",
  "  return { priority: 'normal' }",
  '}',
  '',
  '// router 函数在边层面决策（声明式路由）',
  'const router = (state) => {',
  "  if (state.shouldEnd) return END",
  "  if (state.priority === 'high') return 'priorityHandler'",
  "  if (state.priority === 'critical') return 'escalationHandler'",
  "  return 'normalHandler'",
  '}',
  '',
  'const graphV2 = new StateGraph(AnalyzerState)',
  "  .addNode('analyzer', analyzerNodeV2)",
  "  .addNode('priorityHandler', priorityHandler)",
  "  .addNode('escalationHandler', escalationHandler)",
  "  .addNode('normalHandler', normalHandler)",
  "  .addEdge(START, 'analyzer')",
  "  .addConditionalEdges('analyzer', router)",  // ← 声明式路由',
  "  .addEdge('priorityHandler', END)",
  "  .addEdge('escalationHandler', END)",
  "  .addEdge('normalHandler', END)",
].join('\n')

export const stage4PyCode = [
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.types import Command',
  'from typing import TypedDict',
  '',
  '# ============================================================',
  '# 方式一：Command 命令式路由（节点内决策）',
  '# ============================================================',
  '',
  '# 1. 定义状态',
  'class AnalyzerState(TypedDict):',
  "    text: str",
  "    priority: str",
  "    handled: bool",
  "    handler_note: str",
  '',
  '# 2. analyzer 节点：LLM 分析 + Command 动态路由',
  'def analyzer_node(state: AnalyzerState) -> dict:',
  "    text = state.get('text', '')",
  '',
  '    # ⚡ 用 LLM 分析消息分类',
  "    prompt = f'''请分析以下消息的分类，只返回一个单词：",
  "    - 紧急/故障/宕机 → 返回 'urgent'",
  "    - 投诉/不满/抱怨 → 返回 'complaint'",
  "    - 结束/终止/再见 → 返回 'end'",
  "    - 其他 → 返回 'normal'",
  '',
  '    消息：{text}',
  '',
  "    分类结果：'''",
  '',
  '    response = llm.invoke([HumanMessage(content=prompt)])',
  '    category = response.content.strip().lower()',
  '',
  '    # 🔀 在节点内部根据 LLM 分类结果用 Command 动态路由',
  "    if category == 'urgent':",
  '        return Command(',
  "            goto='priorityHandler',",
  "            update={'priority': 'high', 'handled': True}",
  '        )',
  "    elif category == 'complaint':",
  '        return Command(',
  "            goto='escalationHandler',",
  "            update={'priority': 'critical', 'handled': True}",
  '        )',
  "    elif category == 'end':",
  '        return Command(',
  '            goto=END,',
  "            update={'handled': True}",
  '        )',
  '',
  '    # ➡️ 普通消息 → 不返回 Command，走默认边',
  "    return {'priority': 'normal', 'handled': False}",
  '',
  '# 3. 各处理节点',
  'def priority_handler(state: AnalyzerState) -> dict:',
  "    return {'handler_note': f\"[优先处理] 已紧急响应: {state['text'][:50]}\"}",
  '',
  'def escalation_handler(state: AnalyzerState) -> dict:',
  "    return {'handler_note': f\"[升级处理] 已升级投诉: {state['text'][:50]}\"}",
  '',
  'def normal_handler(state: AnalyzerState) -> dict:',
  "    return {'handler_note': f\"[普通处理] 已记录: {state['text'][:50]}\", 'handled': True}",
  '',
  '# 4. 构建图',
  'graph = StateGraph(AnalyzerState)',
  "graph.add_node('analyzer', analyzer_node)",
  "graph.add_node('priorityHandler', priority_handler)",
  "graph.add_node('escalationHandler', escalation_handler)",
  "graph.add_node('normalHandler', normal_handler)",
  "graph.add_edge(START, 'analyzer')",
  "graph.add_edge('priorityHandler', END)",
  "graph.add_edge('escalationHandler', END)",
  "graph.add_edge('normalHandler', END)",
  '',
  '# 5. 编译并执行',
  'app = graph.compile()',
  "result = app.invoke({'text': '紧急！服务器宕机了'})",
  '',
  '',
  '# ============================================================',
  '# 方式二：条件边 声明式路由（对比）',
  '# ============================================================',
  '',
  '# 条件边版本：同样使用 LLM 分类，仅路由方式不同',
  '# 节点只负责设置状态字段，路由逻辑在边层面的 router 函数中',
  'def analyzer_node_v2(state: AnalyzerState) -> dict:',
  "    text = state.get('text', '')",
  '',
  '    # ⚡ 用 LLM 分析消息分类（与 Command 模式相同的 prompt）',
  "    prompt = f'''请分析以下消息的分类，只返回一个单词：",
  "    - 紧急/故障/宕机 → 返回 'urgent'",
  "    - 投诉/不满/抱怨 → 返回 'complaint'",
  "    - 结束/终止/再见 → 返回 'end'",
  "    - 其他 → 返回 'normal'",
  '',
  '    消息：{text}',
  '',
  "    分类结果：'''",
  '',
  '    response = llm.invoke([HumanMessage(content=prompt)])',
  '    category = response.content.strip().lower()',
  '',
  '    # 根据 LLM 分类结果设置状态字段（不直接路由）',
  "    if category == 'urgent': return {'priority': 'high'}",
  "    if category == 'complaint': return {'priority': 'critical'}",
  "    if category == 'end': return {'should_end': True}",
  "    return {'priority': 'normal'}",
  '',
  'def router(state: AnalyzerState) -> str:',
  "    if state.get('should_end'): return END",
  "    if state.get('priority') == 'high': return 'priorityHandler'",
  "    if state.get('priority') == 'critical': return 'escalationHandler'",
  "    return 'normalHandler'",
  '',
  'graph_v2 = StateGraph(AnalyzerState)',
  "graph_v2.add_node('analyzer', analyzer_node_v2)",
  "graph_v2.add_node('priorityHandler', priority_handler)",
  "graph_v2.add_node('escalationHandler', escalation_handler)",
  "graph_v2.add_node('normalHandler', normal_handler)",
  "graph_v2.add_edge(START, 'analyzer')",
  "graph_v2.add_conditional_edges('analyzer', router)  # ← 声明式路由",
  "graph_v2.add_edge('priorityHandler', END)",
  "graph_v2.add_edge('escalationHandler', END)",
  "graph_v2.add_edge('normalHandler', END)",
].join('\n')