/**
 * LangGraph 各阶段 JS/Python 对比代码示例
 * 存放所有阶段的代码示例，供各 Stage 组件引用
 */

export const stage1JsCode = [
  "import { StateGraph, Annotation, START, END } from '@langchain/langgraph'",
  '',
  '// 1. 定义状态（JS 版：用 Annotation.Root）',
  'const stateDefinition = Annotation.Root({',
  '  text: Annotation(),',
  '  step: Annotation(),',
  '})',
  '',
  '// 2. 定义节点函数（返回 Partial<State>）',
  'const nodeA = (state) => ({',
  '  text: `[A处理] ${state.text}`,',
  "  step: 'A',",
  '})',
  '',
  'const nodeB = (state) => ({',
  '  text: `${state.text} → [B追加]`,',
  "  step: 'B',",
  '})',
  '',
  '// 3. 构建图（链式调用）',
  'const graph = new StateGraph(stateDefinition)',
  "  .addNode('nodeA', nodeA)",
  "  .addNode('nodeB', nodeB)",
  "  .addEdge(START, 'nodeA')   // JS 版：用 addEdge 设置入口",
  "  .addEdge('nodeA', 'nodeB')",
  "  .addEdge('nodeB', END)",
  '',
  '// 4. 编译图',
  'const app = graph.compile()',
  '',
  '// 5. 执行图',
  "const result = await app.invoke({ text: '输入文本' })",
  'console.log(result) // { text: \'...\', step: \'B\' }',
].join('\n')

export const stage1PyCode = [
  'from langgraph.graph import StateGraph, START, END',
  'from typing import TypedDict',
  '',
  '# 1. 定义状态（Python 版：用 TypedDict 类）',
  'class State(TypedDict):',
  '    text: str',
  '    step: str',
  '',
  '# 2. 定义节点函数（返回 dict）',
  'def node_a(state: State) -> dict:',
  `    return {'text': f'[A处理] {state["text"]}', 'step': 'A'}`,
  '',
  'def node_b(state: State) -> dict:',
  `    return {'text': f'{state["text"]} → [B追加]', 'step': 'B'}`,
  '',
  '# 3. 构建图（链式调用）',
  'graph = StateGraph(State)',
  "graph.add_node('node_a', node_a)",
  "graph.add_node('node_b', node_b)",
  "graph.add_edge(START, 'node_a')  # Python 版：也可用 add_edge",
  "graph.add_edge('node_a', 'node_b')",
  "graph.add_edge('node_b', END)",
  '',
  '# 4. 编译图',
  'app = graph.compile()',
  '',
  '# 5. 执行图',
  "result = app.invoke({'text': '输入文本'})",
  "print(result)  # {'text': '...', 'step': 'B'}",
].join('\n')

export const stage2JsCode = [
  "import { StateGraph, Annotation, START, END } from '@langchain/langgraph'",
  "import { messagesStateReducer } from '@langchain/langgraph'",
  '',
  '// ============================================================',
  '// 阶段二核心：Annotation 状态定义 — 三种 Reducer 类型',
  '// ============================================================',
  '',
  '// 1. 定义状态（使用 Annotation.Root + 三种 reducer）',
  'const stateDefinition = Annotation.Root({',
  '  // ① 带 reducer 的状态键：追加消息列表',
  '  //    官网推荐使用 messagesStateReducer（支持 RemoveMessage、ID 去重）',
  '  messages: Annotation<string[]>({',
  '    reducer: (left, right) => left.concat(right),',
  '    default: () => [],',
  '  }),',
  '  // ② 带 reducer 的状态键：累加计数器',
  '  counter: Annotation<number>({',
  '    reducer: (left, right) => left + right,',
  '    default: () => 0,',
  '  }),',
  '  // ③ 简单状态键：LastValue（默认覆盖）',
  '  //    Annotation<string>() 等价于 Annotation<string>({})',
  '  currentStep: Annotation<string>({',
  "    default: () => '未开始',",
  '  }),',
  '})',
  '',
  '// 2. 类型推导（AnnotationRoot 内置 .State / .Update / .Node）',
  'type State = typeof stateDefinition.State',
  '  → { messages: string[], counter: number, currentStep: string }',
  'type Update = typeof stateDefinition.Update',
  '  → Partial<State>（所有字段可选）',
  'type NodeFn = typeof stateDefinition.Node',
  '  → (state: State) => Update | Partial<State>',
  '',
  '// 3. 定义节点函数（返回 Partial<State>）',
  'const nodeA = (state) => ({',
  '  messages: [`[A] ${new Date().toLocaleTimeString()} 收到: ${state.input}`],',
  '  counter: 1,          // 累加：当前值 + 1',
  "  currentStep: 'nodeA', // 覆盖：直接替换",
  '})',
  '',
  'const nodeB = (state) => ({',
  '  messages: [`[B] 处理完成，共 ${state.messages.length + 1} 条消息`],',
  '  counter: 1,          // 累加：当前值 + 1',
  "  currentStep: 'nodeB', // 覆盖：直接替换",
  '})',
  '',
  '// 4. 构建图',
  'const graph = new StateGraph(stateDefinition)',
  "  .addNode('nodeA', nodeA)",
  "  .addNode('nodeB', nodeB)",
  "  .addEdge(START, 'nodeA')",
  "  .addEdge('nodeA', 'nodeB')",
  "  .addEdge('nodeB', END)",
  '',
  '// 5. 编译并执行',
  'const app = graph.compile()',
  "const result = await app.invoke({ input: 'Hello' })",
  "result.messages: ['[A] ...', '[B] ...']  ← 两条消息都被保留",
  'result.counter: 2                          ← 1 + 1 = 2（累加）',
  "result.currentStep: 'nodeB'                ← 被 nodeB 覆盖",
  '',
  '// ============================================================',
  '// 补充：使用 MessagesAnnotation 预构建状态（官网推荐方式）',
  '// ============================================================',
  'import { MessagesAnnotation, StateGraph } from "@langchain/langgraph"',
  'MessagesAnnotation 内部等价于：',
  'Annotation.Root({',
  '  messages: Annotation<BaseMessage[]>({',
  '     reducer: messagesStateReducer,  // 支持 RemoveMessage、ID 去重',
  '     default: () => [],',
  '   }),',
  ' })',
  '',
  'const graph = new StateGraph(MessagesAnnotation)',
  '   .addNode(...)',
  '   .compile()',
].join('\n')

export const stage2PyCode = [
  'from typing import TypedDict, Annotated',
  'import operator',
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.graph import MessagesState  # 预构建消息状态',
  '',
  '# ============================================================',
  '# Python 版：使用 TypedDict + Annotated 定义状态',
  '# ============================================================',
  '',
  '# 1. 定义状态（Python 版：用 TypedDict + Annotated）',
  'class State(TypedDict):',
  '    # ① 追加消息列表（operator.add 等同于 list concatenation）',
  '    messages: Annotated[list[str], operator.add]',
  '    # ② 累加计数器',
  '    counter: Annotated[int, operator.add]',
  '    # ③ 简单覆盖（默认行为，无需 Annotated）',
  '    current_step: str',
  '',
  '# 2. 定义节点函数（返回 dict）',
  'def node_a(state: State) -> dict:',
  '    return {',
  "        'messages': ['[A] 收到消息'],",
  "        'counter': 1,          # 累加",
  "        'current_step': 'nodeA' # 覆盖",
  '    }',
  '',
  'def node_b(state: State) -> dict:',
  '    return {',
  "        'messages': ['[B] 处理完成'],",
  "        'counter': 1,          # 累加",
  "        'current_step': 'nodeB' # 覆盖",
  '    }',
  '',
  '# 3. 构建图',
  'graph = StateGraph(State)',
  "graph.add_node('nodeA', node_a)",
  "graph.add_node('nodeB', node_b)",
  "graph.add_edge(START, 'nodeA')",
  "graph.add_edge('nodeA', 'nodeB')",
  "graph.add_edge('nodeB', END)",
  '',
  '# 4. 编译并执行',
  'app = graph.compile()',
  "result = app.invoke({'messages': [], 'counter': 0, 'current_step': ''})",
  "# result['messages']: ['[A] ...', '[B] ...']",
  "# result['counter']: 2",
  "# result['current_step']: 'nodeB'",
  '',
  '',
  '# ============================================================',
  '# 补充：使用 MessagesState 预构建状态（Python 版推荐方式）',
  '# ============================================================',
  '# from langgraph.graph import MessagesState',
  '#',
  '# # MessagesState 内部等价于：',
  '# # class MessagesState(TypedDict):',
  '# #     messages: Annotated[list[BaseMessage], add_messages]',
  '#',
  '# graph = StateGraph(MessagesState)',
  '# graph.add_node(...)',
  '# app = graph.compile()',
].join('\n')

export const stage3JsCode = [
  "import { StateGraph, Annotation, START, END } from '@langchain/langgraph'",
  "import { ToolNode, toolsCondition } from '@langchain/langgraph/prebuilt'",
  "import { ChatOpenAI } from '@langchain/openai'",
  "import { tool } from '@langchain/core/tools'",
  "import { z } from 'zod'",
  '',
  '// 1. 定义工具',
  'const getWeather = tool(async ({ city }) => {',
  "  return `${city}天气：晴，25°C`",
  '}, {',
  "  name: 'get_weather',",
  "  description: '查询城市天气'",
  '  schema: z.object({ city: z.string() })',
  '})',
  '',
  '// 2. 定义状态',
  'const AgentState = Annotation.Root({',
  '  messages: Annotation<BaseMessage[]>({',
  '    reducer: (left, right) => left.concat(right),',
  '    default: () => [],',
  '  }),',
  '})',
  '',
  '// 3. 创建 LLM 并绑定工具',
  "const llm = new ChatOpenAI({ model: '...' })",
  'const llmWithTools = llm.bindTools(tools)',
  '',
  '// 4. agent 节点：调用 LLM',
  'const callModel = async (state) => {',
  '  const response = await llmWithTools.invoke(state.messages)',
  '  return { messages: [response] }',
  '}',
  '',
  '// 5. 构建图',
  '',
  '// ===== 方式一：toolsCondition（推荐） =====',
  'const graph1 = new StateGraph(AgentState)',
  "  .addNode('agent', callModel)",
  "  .addNode('tools', new ToolNode(tools))",
  "  .addEdge(START, 'agent')",
  "  .addConditionalEdges('agent', toolsCondition)",
  "  .addEdge('tools', 'agent')",
  '',
  '// ===== 方式二：自定义 router =====',
  'const graph2 = new StateGraph(AgentState)',
  "  .addNode('agent', callModel)",
  "  .addNode('tools', new ToolNode(tools))",
  "  .addEdge(START, 'agent')",
  "  .addConditionalEdges('agent', (state) => {",
  '    const lastMsg = state.messages[state.messages.length - 1]',
  "    if (lastMsg.tool_calls?.length > 0) return 'tools'",
  '    return END',
  '  })',
  "  .addEdge('tools', 'agent')",
  '',
  '// 6. 编译并执行',
  'const app = graph1.compile()',
  "const result = await app.invoke({ messages: [new HumanMessage('北京天气')] })",
].join('\n')

export const stage3PyCode = [
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.graph import MessagesState',
  'from langgraph.prebuilt import ToolNode, tools_condition',
  'from langchain_openai import ChatOpenAI',
  '',
  '# 1. 定义工具',
  'def get_weather(city: str) -> str:',
  "    return f'{city}天气：晴，25°C'",
  '',
  '# 2. 创建 LLM 并绑定工具',
  "llm = ChatOpenAI(model='...')",
  'llm_with_tools = llm.bind_tools(tools)',
  '',
  '# 3. agent 节点',
  'def call_model(state: MessagesState) -> dict:',
  '    response = llm_with_tools.invoke(state["messages"])',
  "    return {'messages': [response]}",
  '',
  '# 4. 构建图',
  '',
  '# ===== 方式一：tools_condition（推荐） =====',
  'graph1 = StateGraph(MessagesState)',
  "graph1.add_node('agent', call_model)",
  "graph1.add_node('tools', ToolNode(tools))",
  "graph1.add_edge(START, 'agent')",
  "graph1.add_conditional_edges('agent', tools_condition)",
  "graph1.add_edge('tools', 'agent')",
  '',
  '# ===== 方式二：自定义 router =====',
  'def custom_router(state: MessagesState) -> str:',
  "    last_msg = state['messages'][-1]",
  "    if hasattr(last_msg, 'tool_calls') and last_msg.tool_calls:",
  "        return 'tools'",
  '    return END',
  '',
  'graph2 = StateGraph(MessagesState)',
  "graph2.add_node('agent', call_model)",
  "graph2.add_node('tools', ToolNode(tools))",
  "graph2.add_edge(START, 'agent')",
  "graph2.add_conditional_edges('agent', custom_router)",
  "graph2.add_edge('tools', 'agent')",
  '',
  '# 5. 编译并执行',
  'app = graph1.compile()',
  "result = app.invoke({'messages': [HumanMessage(content='北京天气')]})",
].join('\n')

export const stage4JsCode = [
  "import { StateGraph, Annotation, START, END, Command } from '@langchain/langgraph'",
  "import { ChatOpenAI } from '@langchain/openai'",
  '',
  '// ============================================================',
  '// 方式一：Command 命令式路由（节点内决策）',
  '// ============================================================',
  '',
  '// 1. 定义状态',
  'const AnalyzerState = Annotation.Root({',
  '  text: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => ''",
  '  }),',
  '  priority: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => 'normal'",
  '  }),',
  '  handled: Annotation<boolean>({',
  '    reducer: (_, right) => right,',
  '    default: () => false',
  '  }),',
  '  handlerNote: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => ''",
  '  }),',
  '})',
  '',
  '// 2. analyzer 节点：LLM 分析 + Command 动态路由',
  'const analyzerNode = async (state) => {',
  '  const { text } = state',
  '',
  '  // ⚡ 用 LLM 分析消息分类',
  "  const prompt = `请分析以下消息的分类，只返回一个单词：",
  "  - 紧急/故障/宕机 → 返回 'urgent'",
  "  - 投诉/不满/抱怨 → 返回 'complaint'",
  "  - 结束/终止/再见 → 返回 'end'",
  "  - 其他 → 返回 'normal'",
  '',
  "  消息：${text}",
  '',
  '  分类结果：`',
  '',
  '  const response = await llm.invoke([new HumanMessage(prompt)])',
  "  const category = response.content.trim().toLowerCase()",
  '',
  '  // 🔀 在节点内部根据 LLM 分类结果用 Command 动态路由',
  "  if (category === 'urgent') {",
  '    return new Command({',
  "      goto: 'priorityHandler',",
  "      update: { priority: 'high', handled: true },",
  '    })',
  "  } else if (category === 'complaint') {",
  '    return new Command({',
  "      goto: 'escalationHandler',",
  "      update: { priority: 'critical', handled: true },",
  '    })',
  "  } else if (category === 'end') {",
  '    return new Command({',
  '      goto: END,',
  '      update: { handled: true },',
  '    })',
  '  }',
  '',
  '  // ➡️ 普通消息 → 不返回 Command，走默认边',
  "  return { priority: 'normal', handled: false }",
  '}',
  '',
  '// 3. 各处理节点',
  "const priorityHandler = (state) => ({",
  "  handlerNote: `[优先处理] 已紧急响应: ${state.text.substring(0, 50)}`,",
  '})',
  '',
  "const escalationHandler = (state) => ({",
  "  handlerNote: `[升级处理] 已升级投诉: ${state.text.substring(0, 50)}`,",
  '})',
  '',
  "const normalHandler = (state) => ({",
  "  handlerNote: `[普通处理] 已记录: ${state.text.substring(0, 50)}`,",
  '  handled: true,',
  '})',
  '',
  '// 4. 构建图（注意：使用 Command 的节点需要声明 ends 数组）',
  'const graph = new StateGraph(AnalyzerState)',
  "  .addNode('analyzer', analyzerNode, {",
  "    ends: ['priorityHandler', 'escalationHandler', 'normalHandler', END]",
  '  })',
  "  .addNode('priorityHandler', priorityHandler)",
  "  .addNode('escalationHandler', escalationHandler)",
  "  .addNode('normalHandler', normalHandler)",
  "  .addEdge(START, 'analyzer')",
  "  .addEdge('priorityHandler', END)",
  "  .addEdge('escalationHandler', END)",
  "  .addEdge('normalHandler', END)",
  '',
  '// 5. 编译并执行',
  'const app = graph.compile()',
  "const result = await app.invoke({ text: '紧急！服务器宕机了' })",
  '',
  '',
  '// ============================================================',
  '// 方式二：条件边 声明式路由（对比）',
  '// ============================================================',
  '',
  '// 条件边版本：同样使用 LLM 分类，仅路由方式不同',
  '// 节点只负责设置状态字段，路由逻辑在边层面的 router 函数中',
  'const analyzerNodeV2 = async (state) => {',
  '  const { text } = state',
  '',
  '  // ⚡ 用 LLM 分析消息分类（与 Command 模式相同的 prompt）',
  "  const prompt = `请分析以下消息的分类，只返回一个单词：",
  "  - 紧急/故障/宕机 → 返回 'urgent'",
  "  - 投诉/不满/抱怨 → 返回 'complaint'",
  "  - 结束/终止/再见 → 返回 'end'",
  "  - 其他 → 返回 'normal'",
  '',
  '  消息：${text}',
  '',
  '  分类结果：`',
  '',
  '  const response = await llm.invoke([new HumanMessage(prompt)])',
  "  const category = response.content.trim().toLowerCase()",
  '',
  '  // 根据 LLM 分类结果设置状态字段（不直接路由）',
  "  if (category === 'urgent') return { priority: 'high' }",
  "  if (category === 'complaint') return { priority: 'critical' }",
  "  if (category === 'end') return { shouldEnd: true }",
  "  return { priority: 'normal' }",
  '}',
  '',
  '// router 函数在边层面决策（声明式路由）',
  'const router = (state) => {',
  "  if (state.shouldEnd) return END",
  "  if (state.priority === 'high') return 'priorityHandler'",
  "  if (state.priority === 'critical') return 'escalationHandler'",
  "  return 'normalHandler'",
  '}',
  '',
  'const graphV2 = new StateGraph(AnalyzerState)',
  "  .addNode('analyzer', analyzerNodeV2)",
  "  .addNode('priorityHandler', priorityHandler)",
  "  .addNode('escalationHandler', escalationHandler)",
  "  .addNode('normalHandler', normalHandler)",
  "  .addEdge(START, 'analyzer')",
  "  .addConditionalEdges('analyzer', router)",  // ← 声明式路由',
  "  .addEdge('priorityHandler', END)",
  "  .addEdge('escalationHandler', END)",
  "  .addEdge('normalHandler', END)",
].join('\n')

export const stage4PyCode = [
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.types import Command',
  'from typing import TypedDict',
  '',
  '# ============================================================',
  '# 方式一：Command 命令式路由（节点内决策）',
  '# ============================================================',
  '',
  '# 1. 定义状态',
  'class AnalyzerState(TypedDict):',
  "    text: str",
  "    priority: str",
  "    handled: bool",
  "    handler_note: str",
  '',
  '# 2. analyzer 节点：LLM 分析 + Command 动态路由',
  'def analyzer_node(state: AnalyzerState) -> dict:',
  "    text = state.get('text', '')",
  '',
  '    # ⚡ 用 LLM 分析消息分类',
  "    prompt = f'''请分析以下消息的分类，只返回一个单词：",
  "    - 紧急/故障/宕机 → 返回 'urgent'",
  "    - 投诉/不满/抱怨 → 返回 'complaint'",
  "    - 结束/终止/再见 → 返回 'end'",
  "    - 其他 → 返回 'normal'",
  '',
  '    消息：{text}',
  '',
  "    分类结果：'''",
  '',
  '    response = llm.invoke([HumanMessage(content=prompt)])',
  '    category = response.content.strip().lower()',
  '',
  '    # 🔀 在节点内部根据 LLM 分类结果用 Command 动态路由',
  "    if category == 'urgent':",
  '        return Command(',
  "            goto='priorityHandler',",
  "            update={'priority': 'high', 'handled': True}",
  '        )',
  "    elif category == 'complaint':",
  '        return Command(',
  "            goto='escalationHandler',",
  "            update={'priority': 'critical', 'handled': True}",
  '        )',
  "    elif category == 'end':",
  '        return Command(',
  '            goto=END,',
  "            update={'handled': True}",
  '        )',
  '',
  '    # ➡️ 普通消息 → 不返回 Command，走默认边',
  "    return {'priority': 'normal', 'handled': False}",
  '',
  '# 3. 各处理节点',
  'def priority_handler(state: AnalyzerState) -> dict:',
  "    return {'handler_note': f\"[优先处理] 已紧急响应: {state['text'][:50]}\"}",
  '',
  'def escalation_handler(state: AnalyzerState) -> dict:',
  "    return {'handler_note': f\"[升级处理] 已升级投诉: {state['text'][:50]}\"}",
  '',
  'def normal_handler(state: AnalyzerState) -> dict:',
  "    return {'handler_note': f\"[普通处理] 已记录: {state['text'][:50]}\", 'handled': True}",
  '',
  '# 4. 构建图',
  'graph = StateGraph(AnalyzerState)',
  "graph.add_node('analyzer', analyzer_node)",
  "graph.add_node('priorityHandler', priority_handler)",
  "graph.add_node('escalationHandler', escalation_handler)",
  "graph.add_node('normalHandler', normal_handler)",
  "graph.add_edge(START, 'analyzer')",
  "graph.add_edge('priorityHandler', END)",
  "graph.add_edge('escalationHandler', END)",
  "graph.add_edge('normalHandler', END)",
  '',
  '# 5. 编译并执行',
  'app = graph.compile()',
  "result = app.invoke({'text': '紧急！服务器宕机了'})",
  '',
  '',
  '# ============================================================',
  '# 方式二：条件边 声明式路由（对比）',
  '# ============================================================',
  '',
  '# 条件边版本：同样使用 LLM 分类，仅路由方式不同',
  '# 节点只负责设置状态字段，路由逻辑在边层面的 router 函数中',
  'def analyzer_node_v2(state: AnalyzerState) -> dict:',
  "    text = state.get('text', '')",
  '',
  '    # ⚡ 用 LLM 分析消息分类（与 Command 模式相同的 prompt）',
  "    prompt = f'''请分析以下消息的分类，只返回一个单词：",
  "    - 紧急/故障/宕机 → 返回 'urgent'",
  "    - 投诉/不满/抱怨 → 返回 'complaint'",
  "    - 结束/终止/再见 → 返回 'end'",
  "    - 其他 → 返回 'normal'",
  '',
  '    消息：{text}',
  '',
  "    分类结果：'''",
  '',
  '    response = llm.invoke([HumanMessage(content=prompt)])',
  '    category = response.content.strip().lower()',
  '',
  '    # 根据 LLM 分类结果设置状态字段（不直接路由）',
  "    if category == 'urgent': return {'priority': 'high'}",
  "    if category == 'complaint': return {'priority': 'critical'}",
  "    if category == 'end': return {'should_end': True}",
  "    return {'priority': 'normal'}",
  '',
  'def router(state: AnalyzerState) -> str:',
  "    if state.get('should_end'): return END",
  "    if state.get('priority') == 'high': return 'priorityHandler'",
  "    if state.get('priority') == 'critical': return 'escalationHandler'",
  "    return 'normalHandler'",
  '',
  'graph_v2 = StateGraph(AnalyzerState)',
  "graph_v2.add_node('analyzer', analyzer_node_v2)",
  "graph_v2.add_node('priorityHandler', priority_handler)",
  "graph_v2.add_node('escalationHandler', escalation_handler)",
  "graph_v2.add_node('normalHandler', normal_handler)",
  "graph_v2.add_edge(START, 'analyzer')",
  "graph_v2.add_conditional_edges('analyzer', router)  # ← 声明式路由",
  "graph_v2.add_edge('priorityHandler', END)",
  "graph_v2.add_edge('escalationHandler', END)",
  "graph_v2.add_edge('normalHandler', END)",
].join('\n')

export const stage5JsCode = [
"import { StateGraph, Annotation, START, END, Command, interrupt, MemorySaver } from '@langchain/langgraph'",
  "import { ChatOpenAI } from '@langchain/openai'",
  '',
  '// ============================================================',
  '// 阶段五核心：Human-in-the-Loop — interrupt 人机协同（条件路由）',
  '// ============================================================',
  '',
  '// 1. 定义状态',
  'const ApprovalState = Annotation.Root({',
  '  plan: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => ''",
  '  }),',
  '  approved: Annotation<boolean>({',
  '    reducer: (_, right) => right,',
  '    default: () => false',
  '  }),',
  '  result: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => ''",
  '  }),',
  '})',
  '',
  '// 2. 节点1：生成方案（LLM 驱动）',
  'const generatePlan = async () => {',
  "  const plan = await llm.invoke('请生成一个执行方案...')",
  '  return { plan: plan.content }',
  '}',
  '',
  '// 3. 节点2：等待人工审批（interrupt 暂停）',
  'const waitApproval = (state) => {',
  '  // interrupt() 抛出 GraphInterrupt，暂停图执行',
  '  // 返回值是用户通过 Command({ resume }) 传入的值',
  '  const decision = interrupt({',
  "    question: '请审批以下方案：',",
  '    plan: state.plan,',
  '  })',
  '  // decision 是 resume 传入的值，如 { approved: true, comment: "..." }',
  '  return { approved: decision.approved }',
  '}',
  '',
  '// 4. 节点3：执行方案（仅批准后到达）',
  'const executePlan = () => {',
  "  return { result: '方案已执行，完成资源调配、任务分配、监控启动' }",
  '}',
  '',
  '// 5. 节点4：方案被拒后，LLM 根据反馈重新生成',
  'const revisePlan = async (state) => {',
  "  const newPlan = await llm.invoke(`根据审批意见重新生成方案...`)",
  '  // 返回新方案，重置 approved，循环回 approval 重新审批',
  '  return { plan: newPlan.content, approved: false }',
  '}',
  '',
  '// 6. 条件路由：根据审批结果决定下一步',
  'const routeAfterApproval = (state) => {',
  "  return state.approved ? 'execute' : 'revisePlan'",
  '}',
  '',
  '// 7. 构建图（条件路由 + checkpointer）',
  'const checkpointer = new MemorySaver()',
  'const graph = new StateGraph(ApprovalState)',
  "  .addNode('generate', generatePlan)",
  "  .addNode('approval', waitApproval)",
  "  .addNode('execute', executePlan)",
  "  .addNode('revisePlan', revisePlan)",
  "  .addEdge(START, 'generate')",
  "  .addEdge('generate', 'approval')",
  "  .addConditionalEdges('approval', routeAfterApproval, {",
  "    execute: 'execute',",
  "    revisePlan: 'revisePlan',",
  '  })',
  "  .addEdge('execute', END)",
  "  .addEdge('revisePlan', 'approval')  // ← 循环回 approval 重新审批",
  '',
  'const app = graph.compile({ checkpointer })  // ← 必须注入 checkpointer',
  '',
  '// 8. 第一次调用：执行到 interrupt 处暂停',
  "const threadId = 'thread-1'",
  'const result1 = await app.invoke(',
  "  { plan: '' },",
  '  { configurable: { thread_id: threadId } }',
  ')',
  '// isInterrupted(result1) === true，图暂停在 approval 节点',
  '',
  '// 9. 批准方案：恢复执行 → execute → END',
  'const result2 = await app.invoke(',
  '  new Command({ resume: { approved: true, comment: "同意执行" } }),',
  '  { configurable: { thread_id: threadId } }',
  ')',
  '// isInterrupted(result2) === false，图执行完毕 → END',
  '',
  '// 10. 拒绝方案：恢复执行 → revisePlan(LLM重新生成) → approval(再次interrupt)',
  'const result3 = await app.invoke(',
  '  new Command({ resume: { approved: false, comment: "方案不可行" } }),',
  '  { configurable: { thread_id: threadId } }',
  ')',
  '// isInterrupted(result3) === true，LLM 已重新生成方案，再次暂停等待审批',
].join('\n')

export const stage5PyCode = [
  'from typing import TypedDict',
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.types import Command, interrupt',
  'from langgraph.checkpoint.memory import MemorySaver',
  '',
  '# ============================================================',
  '# Python 版：Human-in-the-Loop — interrupt 人机协同（条件路由）',
  '# ============================================================',
  '',
  '# 1. 定义状态',
  'class ApprovalState(TypedDict):',
  '    plan: str',
  '    approved: bool',
  '    result: str',
  '',
  '# 2. 节点1：生成方案（LLM 驱动）',
  'def generate_plan(state: ApprovalState) -> dict:',
  "    plan = llm.invoke('请生成一个执行方案...')",
  "    return {'plan': plan.content}",
  '',
  '# 3. 节点2：等待人工审批（interrupt 暂停）',
  'def wait_approval(state: ApprovalState) -> dict:',
  '    decision = interrupt({',
  "        'question': '请审批以下方案：',",
  "        'plan': state['plan'],",
  '    })',
  "    return {'approved': decision['approved']}",
  '',
  '# 4. 节点3：执行方案（仅批准后到达）',
  'def execute_plan(state: ApprovalState) -> dict:',
  "    return {'result': '方案已执行，完成资源调配、任务分配、监控启动'}",
  '',
  '# 5. 节点4：方案被拒后，LLM 根据反馈重新生成',
  'def revise_plan(state: ApprovalState) -> dict:',
  "    new_plan = llm.invoke('根据审批意见重新生成方案...')",
  "    return {'plan': new_plan.content, 'approved': False}",
  '',
  '# 6. 条件路由：根据审批结果决定下一步',
  'def route_after_approval(state: ApprovalState) -> str:',
  "    return 'execute' if state['approved'] else 'revise_plan'",
  '',
  '# 7. 构建图（条件路由 + checkpointer）',
  'checkpointer = MemorySaver()',
  'graph = StateGraph(ApprovalState)',
  "graph.add_node('generate', generate_plan)",
  "graph.add_node('approval', wait_approval)",
  "graph.add_node('execute', execute_plan)",
  "graph.add_node('revise_plan', revise_plan)",
  "graph.add_edge(START, 'generate')",
  "graph.add_edge('generate', 'approval')",
  "graph.add_conditional_edges('approval', route_after_approval, {",
  "    'execute': 'execute',",
  "    'revise_plan': 'revise_plan',",
  '})',
  "graph.add_edge('execute', END)",
  "graph.add_edge('revise_plan', 'approval')  # ← 循环回 approval 重新审批",
  '',
  'app = graph.compile(checkpointer=checkpointer)',
  '',
  '# 8. 第一次调用：停在 approval 节点',
  "thread_id = 'thread-1'",
  'result1 = app.invoke(',
  "    {'plan': ''},",
  "    {'configurable': {'thread_id': thread_id}}",
  ')',
  '# result1 包含 __interrupt__，图暂停在 approval 节点',
  '',
  '# 9. 批准方案：恢复执行 → execute → END',
  'result2 = app.invoke(',
  "    Command(resume={'approved': True, 'comment': '同意执行'}),",
  "    {'configurable': {'thread_id': thread_id}}",
  ')',
  '# result2 不包含 __interrupt__，图执行完毕 → END',
  '',
  '# 10. 拒绝方案：恢复执行 → revise_plan(LLM重新生成) → approval(再次interrupt)',
  'result3 = app.invoke(',
  "    Command(resume={'approved': False, 'comment': '方案不可行'}),",
  "    {'configurable': {'thread_id': thread_id}}",
  ')',
  '# result3 包含 __interrupt__，LLM 已重新生成方案，再次暂停等待审批',
].join('\n')

export const stage6JsCode = [
  "import { StateGraph, Annotation, START, END, Send } from '@langchain/langgraph'",
  "import { ChatOpenAI } from '@langchain/openai'",
  "import { HumanMessage } from '@langchain/core/messages'",
  '',
  '// ============================================================',
  '// 阶段六核心：Parallel & Map-Reduce — Send 并行执行',
  '// 场景：对多个文档并行生成摘要，再汇总为最终摘要',
  '// ============================================================',
  '',
  '// 1. 定义状态',
  'const ParallelState = Annotation.Root({',
  '  // 待处理的文档列表（覆盖式）',
  '  documents: Annotation<string[]>({',
  '    reducer: (_, right) => right,',
  '    default: () => [],',
  '  }),',
  '  // 并行摘要结果（追加式：多个 summarizer 实例的输出自动合并）',
  '  summaries: Annotation<string[]>({',
  '    reducer: (left, right) => left.concat(right),',
  '    default: () => [],',
  '  }),',
  '  // 最终汇总摘要（覆盖式）',
  '  finalSummary: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => ''",
  '  }),',
  '})',
  '',
  '// 2. 创建 LLM',
  "const llm = new ChatOpenAI({ model: 'EB-DeepSeek-V4-Pro' })",
  '',
  '// 3. 分发节点：记录日志，不做实际分发',
  'const dispatcher = (state) => {',
  '  // 节点只返回状态更新，不返回 Send[]',
  '  return {}',
  '}',
  '',
  '// 4. 条件边路由函数：为每个文档创建一个 Send（返回 Send[] 触发并行）',
  'const dispatchRouter = (state) => {',
  '  // 为每个文档创建一个并行任务，args 作为该实例的独立输入',
  '  return state.documents.map((doc, i) =>',
  "    new Send('summarizer', { docIndex: i, content: doc })  // JS: new Send",
  '  )',
  '}',
  '',
  '// 5. 并行摘要节点（每个文档一个实例，自动并行执行）',
  'const summarizer = async (state) => {',
  '  const response = await llm.invoke([',
  "    new HumanMessage(`请用一句话摘要以下内容：\\n${state.content}`),",
  '  ])',
  '  // 返回部分更新，reducer 自动合并多个实例的输出',
  '  return { summaries: [`[文档${state.docIndex + 1}] ${response.content}`] }',
  '}',
  '',
  '// 6. 汇总节点：合并所有摘要',
  'const aggregator = async (state) => {',
  '  const response = await llm.invoke([',
  "    new HumanMessage(`请将以下摘要合并为一段连贯的总结：\\n${state.summaries.join('\\n')}`),",
  '  ])',
  '  return { finalSummary: response.content }',
  '}',
  '',
  '// 7. 构建图（节点与条件边路由函数分离）',
  'const graph = new StateGraph(ParallelState)',
  "  .addNode('dispatcher', dispatcher)",
  "  .addNode('summarizer', summarizer)",
  "  .addNode('aggregator', aggregator)",
  "  .addEdge(START, 'dispatcher')",
  "  .addConditionalEdges('dispatcher', dispatchRouter)  // ← 条件边路由函数返回 Send[] 触发并行",
  "  .addEdge('summarizer', 'aggregator')                // ← 所有并行实例完成后进入汇总",
  "  .addEdge('aggregator', END)",
  '',
  'const app = graph.compile()',
  '',
  '// 8. 执行（Map-Reduce：分发 → 并行摘要 → 汇总）',
  'const result = await app.invoke({',
  '  documents: [',
  "    'LangGraph 是一个用于构建状态图工作流的框架...',",
  "    'Send 允许在条件边中动态创建并行任务...',",
  "    'Reducer 负责合并多个并行节点实例的输出...',",
  '  ],',
  '})',
  '// result.summaries: 3 条并行摘要（reducer 自动合并）',
  '// result.finalSummary: 汇总后的最终摘要',
].join('\n')

export const stage6PyCode = [
  'from typing import TypedDict, Annotated',
  'import operator',
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.types import Send',
  'from langchain_openai import ChatOpenAI',
  'from langchain_core.messages import HumanMessage',
  '',
  '# ============================================================',
  '# Python 版：Parallel & Map-Reduce — Send 并行执行',
  '# ============================================================',
  '',
  '# 1. 定义状态',
  'class ParallelState(TypedDict):',
  '    documents: list[str]',
  '    summaries: Annotated[list[str], operator.add]  # 追加式：合并并行结果',
  '    final_summary: str',
  '',
  '# 2. 创建 LLM',
  "llm = ChatOpenAI(model='EB-DeepSeek-V4-Pro')",
  '',
  '# 3. 分发节点：为每个文档创建一个 Send',
  'def dispatcher(state: ParallelState) -> list[Send]:',
  '    return [',
  "        Send('summarizer', {'doc_index': i, 'content': doc})  # Python: Send(...)",
  "        for i, doc in enumerate(state['documents'])",
  '    ]',
  '',
  '# 4. 并行摘要节点',
  'async def summarizer(state: ParallelState) -> dict:',
  '    response = await llm.ainvoke([',
  "        HumanMessage(content=f'请用一句话摘要以下内容：\\n{state[\"content\"]}')",
  '    ])',
  "    return {'summaries': [f'[文档{state[\"doc_index\"] + 1}] {response.content}']}",
  '',
  '# 5. 汇总节点',
  'async def aggregator(state: ParallelState) -> dict:',
  '    response = await llm.ainvoke([',
  "        HumanMessage(content=f'请将以下摘要合并为一段连贯的总结：\\n{chr(10).join(state[\"summaries\"])}')",
  '    ])',
  "    return {'final_summary': response.content}",
  '',
  '# 6. 构建图',
  'graph = StateGraph(ParallelState)',
  "graph.add_node('dispatcher', dispatcher)",
  "graph.add_node('summarizer', summarizer)",
  "graph.add_node('aggregator', aggregator)",
  "graph.add_edge(START, 'dispatcher')",
  "graph.add_conditional_edges('dispatcher', dispatcher)  # ← 返回 list[Send] 触发并行",
  "graph.add_edge('summarizer', 'aggregator')              # ← 所有并行实例完成后进入汇总",
  "graph.add_edge('aggregator', END)",
  '',
  'app = graph.compile()',
  '',
  '# 7. 执行',
  'result = app.invoke({',
  "    'documents': [",
  "        'LangGraph 是一个用于构建状态图工作流的框架...',",
  "        'Send 允许在条件边中动态创建并行任务...',",
  "        'Reducer 负责合并多个并行节点实例的输出...',",
  '    ],',
  '})',
  "# result['summaries']: 3 条并行摘要",
  "# result['final_summary']: 汇总后的最终摘要",
].join('\n')

export const stage7JsCode = [
  "import { MemorySaver } from '@langchain/langgraph'",
  "import { createReactAgent } from '@langchain/langgraph/prebuilt'",
  "import { ChatOpenAI } from '@langchain/openai'",
  "import { tool } from '@langchain/core/tools'",
  "import { z } from 'zod'",
  '',
  '// ============================================================',
  '// 阶段七核心：短期记忆 MemorySaver — Checkpoint 持久化',
  '// ============================================================',
  '',
  '// 1. 创建 MemorySaver 实例（全局单例，所有线程共享）',
  'const memorySaver = new MemorySaver()',
  '',
  '// 2. 定义工具',
  'const calculatorTool = tool(async ({ expression }) => {',
  "  return `计算结果: ${expression} = ${eval(expression)}`",
  '}, {',
  "  name: 'calculator',",
  "  description: '执行数学计算'",
  '  schema: z.object({ expression: z.string() })',
  '})',
  '',
  '// 3. 创建 LLM',
  "const llm = new ChatOpenAI({ model: 'EB-DeepSeek-V4-Pro' })",
  '',
  '// 4. 构建 Agent（核心：注入 checkpointer）',
  'const agent = createReactAgent({',
  '  llm,',
  '  tools: [calculatorTool],',
  '  checkpointer: memorySaver,  // ← 注入 MemorySaver 实现短期记忆',
  "  name: 'AI助手',",
  "  prompt: '你是一个有用的AI助手，请记住对话历史中的上下文信息。回答请用中文。'",
  '})',
  '',
  '// 5. 第一次对话（thread_id = "session-1"）',
  'const config1 = { configurable: { thread_id: "session-1" } }',
  "const result1 = await agent.invoke({ messages: [new HumanMessage('我叫张三')] }, config1)",
  '// → AI 记住了"张三"',
  '',
  '// 6. 第二次对话（同一 thread_id，AI 能记住上下文）',
  "const result2 = await agent.invoke({ messages: [new HumanMessage('我叫什么名字？')] }, config1)",
  '// → AI 回答"你叫张三"（因为 MemorySaver 保存了历史）',
  '',
  '// 7. 不同 thread_id 完全隔离',
  'const config2 = { configurable: { thread_id: "session-2" } }',
  "const result3 = await agent.invoke({ messages: [new HumanMessage('我叫什么名字？')] }, config2)",
  '// → AI 不知道（session-2 是全新会话，无历史记录）',
  '',
  '// ============================================================',
  '// 对比：不注入 checkpointer 的 Agent（无记忆）',
  '// ============================================================',
  'const agentNoMemory = createReactAgent({ llm, tools: [calculatorTool] })',
  '// 每次 invoke 都是全新上下文，无法记住之前的对话',
].join('\n')

export const stage7PyCode = [
  'from langgraph.checkpoint.memory import MemorySaver',
  'from langgraph.prebuilt import create_react_agent',
  'from langchain_openai import ChatOpenAI',
  'from langchain_core.messages import HumanMessage',
  '',
  '# ============================================================',
  '# Python 版：短期记忆 MemorySaver — Checkpoint 持久化',
  '# ============================================================',
  '',
  '# 1. 创建 MemorySaver 实例',
  'memory_saver = MemorySaver()',
  '',
  '# 2. 定义工具',
  'def calculator(expression: str) -> str:',
  "    return f'计算结果: {expression} = {eval(expression)}'",
  '',
  '# 3. 创建 LLM',
  "llm = ChatOpenAI(model='EB-DeepSeek-V4-Pro')",
  '',
  '# 4. 构建 Agent（核心：注入 checkpointer）',
  'agent = create_react_agent(',
  '    llm,',
  '    [calculator],',
  '    checkpointer=memory_saver,  # ← 注入 MemorySaver 实现短期记忆',
  ')',
  '',
  '# 5. 第一次对话（thread_id = "session-1"）',
  "config1 = {'configurable': {'thread_id': 'session-1'}}",
  "result1 = agent.invoke({'messages': [HumanMessage(content='我叫张三')]}, config1)",
  '# → AI 记住了"张三"',
  '',
  '# 6. 第二次对话（同一 thread_id，AI 能记住上下文）',
  "result2 = agent.invoke({'messages': [HumanMessage(content='我叫什么名字？')]}, config1)",
  '# → AI 回答"你叫张三"（因为 MemorySaver 保存了历史）',
  '',
  '# 7. 不同 thread_id 完全隔离',
  "config2 = {'configurable': {'thread_id': 'session-2'}}",
  "result3 = agent.invoke({'messages': [HumanMessage(content='我叫什么名字？')]}, config2)",
  '# → AI 不知道（session-2 是全新会话，无历史记录）',
].join('\n')

export const stage8JsCode = [
  "import { InMemoryStore } from '@langchain/langgraph'",
  "import { createReactAgent } from '@langchain/langgraph/prebuilt'",
  "import { ChatOpenAI } from '@langchain/openai'",
  "import { tool } from '@langchain/core/tools'",
  "import { z } from 'zod'",
  '',
  '// ============================================================',
  '// 阶段八核心：长期记忆 Store — InMemoryStore 跨会话持久化',
  '// ============================================================',
  '',
  '// 1. 创建 InMemoryStore 实例（全局单例，跨用户共享）',
  'const store = new InMemoryStore()',
  '',
  '// 2. 定义记忆工具：remember（存入长期记忆）',
  'const rememberTool = tool(async ({ category, key, content, scope }) => {',
  '  // 根据 scope 构建 namespace',
  "  const namespace = scope === 'shared'",
  "    ? ['shared', category]",
  "    : ['users', userId, category]",
  '',
  '  await store.put(namespace, key, { content, timestamp: Date.now() })',
  "  return `✅ 已存入长期记忆：[${category}] ${key} = ${content}`",
  '}, {',
  "  name: 'remember',",
  "  description: '将信息存入长期记忆'",
  '  schema: z.object({',
  "    category: z.string().describe('记忆分类，如 preferences, facts, skills'),",
  "    key: z.string().describe('记忆键名'),",
  "    content: z.string().describe('记忆内容'),",
  "    scope: z.enum(['private', 'shared']).optional().describe('可见范围'),",
  '  })',
  '})',
  '',
  '// 3. 定义记忆工具：recall（检索长期记忆）',
  'const recallTool = tool(async ({ category, scope }) => {',
  "  const namespace = scope === 'shared'",
  "    ? ['shared', category]",
  "    : ['users', userId, category]",
  '',
  '  const results = await store.search(namespace, { limit: 50 })',
  '  if (results.length === 0) return "未找到相关记忆"',
  '',
  '  return results.map((item) =>',
  "    `- [${item.namespace.join('/')}] ${item.key}: ${item.value.content}`",
  '  ).join("\\n")',
  '}, {',
  "  name: 'recall',",
  "  description: '检索长期记忆'",
  '  schema: z.object({',
  "    category: z.string().optional().describe('记忆分类'),",
  "    scope: z.enum(['private', 'shared']).optional().describe('搜索范围'),",
  '  })',
  '})',
  '',
  '// 4. 创建 LLM',
  "const llm = new ChatOpenAI({ model: 'EB-DeepSeek-V4-Pro' })",
  '',
  '// 5. 构建 Agent（核心：注入 store）',
  'const agent = createReactAgent({',
  '  llm,',
  '  tools: [rememberTool, recallTool],',
  '  store: store,  // ← 注入 InMemoryStore 实现长期记忆',
  "  name: 'AI助手（带长期记忆）',",
  "  prompt: '你是一个具有长期记忆能力的AI助手。在回答前先用 recall 检索记忆，用户分享信息时用 remember 保存。'",
  '})',
  '',
  '// 6. 用户 A 存入记忆',
  "const configA = { configurable: { thread_id: 'user-a' } }",
  "await agent.invoke({ messages: [new HumanMessage('我叫张三，喜欢编程')] }, configA)",
  '// → AI 调用 remember 工具存入长期记忆',
  '',
  '// 7. 用户 A 新会话仍能检索到记忆（跨会话持久化）',
  "const configA2 = { configurable: { thread_id: 'user-a-session2' } }",
  "await agent.invoke({ messages: [new HumanMessage('我喜欢什么？')] }, configA2)",
  '// → AI 调用 recall 工具检索到"喜欢编程"',
  '',
  '// ============================================================',
  '// 三种记忆模式',
  '// ============================================================',
  '// isolated: namespace = ["users", userId, category] — 完全隔离',
  '// shared:   namespace = ["shared", category] — 所有用户共享',
  '// hybrid:   同时搜索私有和共享 namespace',
].join('\n')

export const stage8PyCode = [
  'from langgraph.store.memory import InMemoryStore',
  'from langgraph.prebuilt import create_react_agent',
  'from langchain_openai import ChatOpenAI',
  'from langchain_core.messages import HumanMessage',
  '',
  '# ============================================================',
  '# Python 版：长期记忆 Store — InMemoryStore 跨会话持久化',
  '# ============================================================',
  '',
  '# 1. 创建 InMemoryStore 实例',
  'store = InMemoryStore()',
  '',
  '# 2. 定义记忆工具：remember（存入长期记忆）',
  'def remember(category: str, key: str, content: str, scope: str = "private") -> str:',
  '    # 根据 scope 构建 namespace',
  "    namespace = ('shared', category) if scope == 'shared' else ('users', user_id, category)",
  "    store.put(namespace, key, {'content': content, 'timestamp': time.time()})",
  "    return f'✅ 已存入长期记忆：[{category}] {key} = {content}'",
  '',
  '# 3. 定义记忆工具：recall（检索长期记忆）',
  'def recall(category: str = None, scope: str = "private") -> str:',
  "    namespace = ('shared', category) if scope == 'shared' else ('users', user_id, category)",
  '    results = list(store.search(namespace, limit=50))',
  '    if not results:',
  '        return "未找到相关记忆"',
  "    return '\\n'.join([f\"- [{item.namespace}] {item.key}: {item.value['content']}\" for item in results])",
  '',
  '# 4. 创建 LLM',
  "llm = ChatOpenAI(model='EB-DeepSeek-V4-Pro')",
  '',
  '# 5. 构建 Agent（核心：注入 store）',
  'agent = create_react_agent(',
  '    llm,',
  '    [remember, recall],',
  '    store=store,  # ← 注入 InMemoryStore 实现长期记忆',
  ')',
  '',
  '# 6. 用户 A 存入记忆',
  "config_a = {'configurable': {'thread_id': 'user-a'}}",
  "agent.invoke({'messages': [HumanMessage(content='我叫张三，喜欢编程')]}, config_a)",
  '',
  '# 7. 用户 A 新会话仍能检索到记忆（跨会话持久化）',
  "config_a2 = {'configurable': {'thread_id': 'user-a-session2'}}",
  "agent.invoke({'messages': [HumanMessage(content='我喜欢什么？')]}, config_a2)",
  '# → AI 调用 recall 工具检索到"喜欢编程"',
].join('\n')

export const stage9JsCode = [
  "import { StateGraph, Annotation, START, END, MemorySaver } from '@langchain/langgraph'",
  "import { ChatOpenAI } from '@langchain/openai'",
  "import { HumanMessage, AIMessage } from '@langchain/core/messages'",
  '',
  '// ============================================================',
  '// 阶段九核心：Checkpoint 检查点 — getState/getStateHistory + Time Travel',
  '// ============================================================',
  '',
  '// 1. 定义状态',
  'const GraphState = Annotation.Root({',
  '  messages: Annotation<BaseMessage[]>({',
  '    reducer: (prev, next) => prev.concat(next),',
  '    default: () => [],',
  '  }),',
  '})',
  '',
  '// 2. 创建 LLM',
  "const llm = new ChatOpenAI({ model: 'EB-DeepSeek-V4-Pro' })",
  '',
  '// 3. 定义节点',
  'const chatNode = async (state) => {',
  '  const response = await llm.invoke(state.messages)',
  '  return { messages: [response] }',
  '}',
  '',
  '// 4. 构建图（必须注入 checkpointer）',
  'const memorySaver = new MemorySaver()',
  'const graph = new StateGraph(GraphState)',
  "  .addNode('chat', chatNode)",
  "  .addEdge(START, 'chat')",
  "  .addEdge('chat', END)",
  '',
  'const app = graph.compile({ checkpointer: memorySaver })',
  '',
  '// 5. 执行对话（生成检查点）',
  "const config = { configurable: { thread_id: 'demo-1' } }",
  "await app.invoke({ messages: [new HumanMessage('我叫张三')] }, config)",
  "await app.invoke({ messages: [new HumanMessage('我今年25岁')] }, config)",
  "await app.invoke({ messages: [new HumanMessage('我喜欢编程')] }, config)",
  '',
  '// ============================================================',
  '// getState — 查看当前状态快照',
  '// ============================================================',
  'const snapshot = await app.getState(config)',
  '// StateSnapshot {',
  '//   values: { messages: [...] },        // 当前状态值',
  '//   next: [],                            // 下一个待执行节点（空=已完成）',
  '//   config: { configurable: {',
  '//     thread_id: "demo-1",',
  '//     checkpoint_id: "1ef7e..."         // 当前检查点 ID',
  '//   }},',
  '//   metadata: { source: "loop", step: 3 },',
  '//   createdAt: "2026-09-24T...",',
  '//   parentConfig: { configurable: {',
  '//     checkpoint_id: "1ef7d..."         // 父检查点 ID',
  '//   }}',
  '// }',
  '',
  '// ============================================================',
  '// getStateHistory — 遍历历史检查点',
  '// ============================================================',
  'const history = []',
  'for await (const snapshot of app.getStateHistory(config)) {',
  '  history.push({',
  '    checkpointId: snapshot.config?.configurable?.checkpoint_id,',
  '    messageCount: snapshot.values?.messages?.length || 0,',
  '    step: snapshot.metadata?.step,',
  '    createdAt: snapshot.createdAt,',
  '    parentCheckpointId: snapshot.parentConfig?.configurable?.checkpoint_id,',
  '  })',
  '}',
  '// history 按时间倒序排列（最新在前）',
  '',
  '// ============================================================',
  '// Time Travel: 回放（Replay）— 从历史检查点重新执行',
  '// ============================================================',
  '// 选择第2个检查点（"我今年25岁"之后）',
  'const targetCp = history[1]',
  '// 传入 null 表示不追加新输入，仅重放到该检查点',
  'const replayResult = await app.invoke(null, targetCp.config)',
  '// replayResult.messages 只包含前2轮对话',
  '',
  '// ============================================================',
  '// Time Travel: 分叉（Fork）— 从历史检查点走不同路径',
  '// ============================================================',
  '// 从第2个检查点分叉，追加新消息',
  'const forkResult = await app.invoke(',
  "  { messages: [new HumanMessage('其实我30岁，喜欢打篮球')] },",
  '  targetCp.config  // ← 使用历史检查点的 config',
  ')',
  '// forkResult 创建了新的时间线分支（新 checkpoint_id，parentCheckpointId 指向 targetCp）',
].join('\n')

export const stage9PyCode = [
  'from typing import TypedDict, Annotated',
  'import operator',
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.checkpoint.memory import MemorySaver',
  'from langchain_openai import ChatOpenAI',
  'from langchain_core.messages import HumanMessage',
  '',
  '# ============================================================',
  '# Python 版：Checkpoint 检查点 — getState/getStateHistory + Time Travel',
  '# ============================================================',
  '',
  '# 1. 定义状态',
  'class State(TypedDict):',
  '    messages: Annotated[list, operator.add]',
  '',
  '# 2. 创建 LLM',
  "llm = ChatOpenAI(model='EB-DeepSeek-V4-Pro')",
  '',
  '# 3. 定义节点',
  'def chat_node(state: State) -> dict:',
  "    response = llm.invoke(state['messages'])",
  "    return {'messages': [response]}",
  '',
  '# 4. 构建图（必须注入 checkpointer）',
  'memory_saver = MemorySaver()',
  'graph = StateGraph(State)',
  "graph.add_node('chat', chat_node)",
  "graph.add_edge(START, 'chat')",
  "graph.add_edge('chat', END)",
  '',
  'app = graph.compile(checkpointer=memory_saver)',
  '',
  '# 5. 执行对话（生成检查点）',
  "config = {'configurable': {'thread_id': 'demo-1'}}",
  "app.invoke({'messages': [HumanMessage(content='我叫张三')]}, config)",
  "app.invoke({'messages': [HumanMessage(content='我今年25岁')]}, config)",
  "app.invoke({'messages': [HumanMessage(content='我喜欢编程')]}, config)",
  '',
  '# ============================================================',
  '# get_state — 查看当前状态快照',
  '# ============================================================',
  'snapshot = app.get_state(config)',
  '# StateSnapshot {',
  '#   values: { messages: [...] },',
  '#   next: (),',
  '#   config: { configurable: {',
  '#     thread_id: "demo-1",',
  '#     checkpoint_id: "1ef7e..."',
  '#   }},',
  '#   metadata: { source: "loop", step: 3 },',
  '#   created_at: "2026-09-24T...",',
  '#   parent_config: { configurable: {',
  '#     checkpoint_id: "1ef7d..."',
  '#   }}',
  '# }',
  '',
  '# ============================================================',
  '# get_state_history — 遍历历史检查点',
  '# ============================================================',
  'history = []',
  'for snapshot in app.get_state_history(config):',
  '    history.append({',
  "        'checkpoint_id': snapshot.config['configurable']['checkpoint_id'],",
  "        'message_count': len(snapshot.values.get('messages', [])),",
  "        'step': snapshot.metadata.get('step'),",
  "        'created_at': snapshot.created_at,",
  "        'parent_checkpoint_id': snapshot.parent_config['configurable'].get('checkpoint_id'),",
  '    })',
  '# history 按时间倒序排列（最新在前）',
  '',
  '# ============================================================',
  '# Time Travel: 回放（Replay）— 从历史检查点重新执行',
  '# ============================================================',
  '# 选择第2个检查点（"我今年25岁"之后）',
  'target_cp = history[1]',
  '# 传入 None 表示不追加新输入，仅重放到该检查点',
  "replay_result = app.invoke(None, target_cp['config'])",
  "# replay_result['messages'] 只包含前2轮对话",
  '',
  '# ============================================================',
  '# Time Travel: 分叉（Fork）— 从历史检查点走不同路径',
  '# ============================================================',
  '# 从第2个检查点分叉，追加新消息',
  'fork_result = app.invoke(',
  "    {'messages': [HumanMessage(content='其实我30岁，喜欢打篮球')]},",
  "    target_cp['config']  # ← 使用历史检查点的 config",
  ')',
  '# fork_result 创建了新的时间线分支',
].join('\n')

export const stage10JsCode = [
  "import { StateGraph, Annotation, START, END, MemorySaver } from '@langchain/langgraph'",
  "import { ChatOpenAI } from '@langchain/openai'",
  "import { HumanMessage, SystemMessage } from '@langchain/core/messages'",
  '',
  '// ============================================================',
  '// 阶段十核心：运行时上下文 Context — runtime.context 注入与使用',
  '// ============================================================',
  '',
  '// 1. 定义上下文结构（contextSchema）',
  '//    使用 Annotation.Root() 定义运行时上下文的字段',
  'const ContextSchema = Annotation.Root({',
  '  username: Annotation<string>,   // 用户名',
  '  level: Annotation<string>,      // 会员等级',
  '  lang: Annotation<string>,       // 语言偏好',
  '})',
  '',
  '// 2. 定义图状态',
  'const GraphState = Annotation.Root({',
  '  messages: Annotation<BaseMessage[]>({',
  '    reducer: (prev, next) => prev.concat(next),',
  '    default: () => [],',
  '  }),',
  '})',
  '',
  '// 3. 创建 LLM',
  "const llm = new ChatOpenAI({ model: 'EB-DeepSeek-V4-Pro' })",
  '',
  '// 4. 节点函数：通过 runtime.context 访问上下文',
  '//    注意：第二个参数 runtime 由 LangGraph 自动注入',
  'const chatNode = async (state, runtime) => {',
  '  // 从 runtime.context 读取运行时上下文',
  '  const ctx = runtime.context || {}',
  "  const username = ctx.username || '用户'",
  "  const level = ctx.level || 'normal'",
  "  const lang = ctx.lang || 'zh-CN'",
  '',
  '  // 根据上下文构建系统提示',
  '  let systemPrompt = `你是一个有用的AI助手。当前用户是${username}，会员等级：${level}。`',
  "  if (level === 'VIP') {",
  '    systemPrompt += " 请以VIP会员的规格提供服务，语气热情周到。"',
  "  } else if (level === 'SVIP') {",
  '    systemPrompt += " 请以最高规格的SVIP至尊会员服务标准回复，使用尊称。"',
  '  }',
  "  if (lang === 'en') {",
  '    systemPrompt = `You are a helpful AI assistant. Current user: ${username}, level: ${level}. Reply in English.`',
  '  }',
  '',
  '  const messages = [new SystemMessage(systemPrompt), ...state.messages]',
  '  const response = await llm.invoke(messages)',
  '  return { messages: [response] }',
  '}',
  '',
  '// 5. 构建图（传入 contextSchema）',
  '//    StateGraph 构造函数第二个参数是 contextSchema',
  'const memorySaver = new MemorySaver()',
  'const graph = new StateGraph(GraphState, ContextSchema)  // ← 传入 ContextSchema',
  "  .addNode('chat', chatNode)",
  "  .addEdge(START, 'chat')",
  "  .addEdge('chat', END)",
  '',
  'const app = graph.compile({ checkpointer: memorySaver })',
  '',
  '// 6. 调用时通过 config.context 传入运行时上下文',
  'const config = {',
  "  configurable: { thread_id: 'ctx-demo-1' },",
  '  context: {',
  "    username: '张三',",
  "    level: 'VIP',",
  "    lang: 'zh-CN',",
  '  }',
  '}',
  '',
  "const result = await app.invoke({ messages: [new HumanMessage('你好，介绍一下你自己')] }, config)",
  '// → AI 以 VIP 会员规格回复，称呼"张三"',
  '',
  '// 7. 切换上下文（同一 thread_id，不同用户）',
  'const config2 = {',
  "  configurable: { thread_id: 'ctx-demo-1' },",
  '  context: {',
  "    username: '李四',",
  "    level: 'normal',",
  "    lang: 'en',",
  '  }',
  '}',
  "const result2 = await app.invoke({ messages: [new HumanMessage('Hello, introduce yourself')] }, config2)",
  '// → AI 以普通用户规格用英文回复，称呼"李四"',
  '',
  '// ============================================================',
  '// 关键区别：context vs state',
  '// ============================================================',
  '// state:   图执行过程中可变的状态（有 reducer、持久化到 checkpoint）',
  '// context: 运行时注入的只读配置（不参与 reducer、不持久化到 checkpoint）',
  '//          适合传递：用户身份、权限、语言偏好、租户 ID 等',
].join('\n')

export const stage10PyCode = [
  'from typing import TypedDict, Annotated',
  'import operator',
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.graph import add_messages',
  'from langgraph.checkpoint.memory import MemorySaver',
  'from langchain_openai import ChatOpenAI',
  'from langchain_core.messages import HumanMessage, SystemMessage',
  '',
  '# ============================================================',
  '# Python 版：运行时上下文 Context — runtime.context 注入与使用',
  '# ============================================================',
  '',
  '# 1. 定义上下文结构（contextSchema）',
  '#    Python 版使用 TypedDict 定义上下文',
  'from typing import TypedDict',
  '',
  'class ContextSchema(TypedDict):',
  '    username: str    # 用户名',
  '    level: str       # 会员等级',
  '    lang: str        # 语言偏好',
  '',
  '# 2. 定义图状态',
  'class State(TypedDict):',
  '    messages: Annotated[list, add_messages]',
  '',
  '# 3. 创建 LLM',
  "llm = ChatOpenAI(model='EB-DeepSeek-V4-Pro')",
  '',
  '# 4. 节点函数：通过 runtime.context 访问上下文',
  '#    注意：第二个参数 runtime 由 LangGraph 自动注入',
  'def chat_node(state: State, runtime) -> dict:',
  '    # 从 runtime.context 读取运行时上下文',
  "    ctx = runtime.context or {}",
  "    username = ctx.get('username', '用户')",
  "    level = ctx.get('level', 'normal')",
  "    lang = ctx.get('lang', 'zh-CN')",
  '',
  '    # 根据上下文构建系统提示',
  "    system_prompt = f'你是一个有用的AI助手。当前用户是{username}，会员等级：{level}。'",
  "    if level == 'VIP':",
  '        system_prompt += " 请以VIP会员的规格提供服务，语气热情周到。"',
  "    elif level == 'SVIP':",
  '        system_prompt += " 请以最高规格的SVIP至尊会员服务标准回复，使用尊称。"',
  "    if lang == 'en':",
  "        system_prompt = f'You are a helpful AI assistant. Current user: {username}, level: {level}. Reply in English.'",
  '',
  "    messages = [SystemMessage(content=system_prompt)] + state['messages']",
  '    response = llm.invoke(messages)',
  "    return {'messages': [response]}",
  '',
  '# 5. 构建图（传入 contextSchema）',
  'memory_saver = MemorySaver()',
  'graph = StateGraph(State, context_schema=ContextSchema)  # ← 传入 ContextSchema',
  "graph.add_node('chat', chat_node)",
  "graph.add_edge(START, 'chat')",
  "graph.add_edge('chat', END)",
  '',
  'app = graph.compile(checkpointer=memory_saver)',
  '',
  '# 6. 调用时通过 config.context 传入运行时上下文',
  'config = {',
  "    'configurable': {'thread_id': 'ctx-demo-1'},",
  "    'context': {",
  "        'username': '张三',",
  "        'level': 'VIP',",
  "        'lang': 'zh-CN',",
  '    }',
  '}',
  '',
  "result = app.invoke({'messages': [HumanMessage(content='你好，介绍一下你自己')]}, config)",
  '# → AI 以 VIP 会员规格回复，称呼"张三"',
  '',
  '# 7. 切换上下文（同一 thread_id，不同用户）',
  'config2 = {',
  "    'configurable': {'thread_id': 'ctx-demo-1'},",
  "    'context': {",
  "        'username': '李四',",
  "        'level': 'normal',",
  "        'lang': 'en',",
  '    }',
  '}',
  "result2 = app.invoke({'messages': [HumanMessage(content='Hello, introduce yourself')]}, config2)",
  '# → AI 以普通用户规格用英文回复，称呼"李四"',
].join('\n')
