/**
 * LangGraph 各阶段 JS/Python 对比代码示例
 * 存放所有阶段的代码示例，供各 Stage 组件引用
 */

export const stage1JsCode = [
  "import { StateGraph, Annotation, START, END } from '@langchain/langgraph'",
  '',
  '// 1. 定义状态（JS 版：用 Annotation.Root）',
  'const stateDefinition = Annotation.Root({',
  '  text: Annotation(),',
  '  step: Annotation(),',
  '})',
  '',
  '// 2. 定义节点函数（返回 Partial<State>）',
  'const nodeA = (state) => ({',
  '  text: `[A处理] ${state.text}`,',
  "  step: 'A',",
  '})',
  '',
  'const nodeB = (state) => ({',
  '  text: `${state.text} → [B追加]`,',
  "  step: 'B',",
  '})',
  '',
  '// 3. 构建图（链式调用）',
  'const graph = new StateGraph(stateDefinition)',
  "  .addNode('nodeA', nodeA)",
  "  .addNode('nodeB', nodeB)",
  "  .addEdge(START, 'nodeA')   // JS 版：用 addEdge 设置入口",
  "  .addEdge('nodeA', 'nodeB')",
  "  .addEdge('nodeB', END)",
  '',
  '// 4. 编译图',
  'const app = graph.compile()',
  '',
  '// 5. 执行图',
  "const result = await app.invoke({ text: '输入文本' })",
  'console.log(result) // { text: \'...\', step: \'B\' }',
].join('\n')

export const stage1PyCode = [
  'from langgraph.graph import StateGraph, START, END',
  'from typing import TypedDict',
  '',
  '# 1. 定义状态（Python 版：用 TypedDict 类）',
  'class State(TypedDict):',
  '    text: str',
  '    step: str',
  '',
  '# 2. 定义节点函数（返回 dict）',
  'def node_a(state: State) -> dict:',
  `    return {'text': f'[A处理] {state["text"]}', 'step': 'A'}`,
  '',
  'def node_b(state: State) -> dict:',
  `    return {'text': f'{state["text"]} → [B追加]', 'step': 'B'}`,
  '',
  '# 3. 构建图（链式调用）',
  'graph = StateGraph(State)',
  "graph.add_node('node_a', node_a)",
  "graph.add_node('node_b', node_b)",
  "graph.add_edge(START, 'node_a')  # Python 版：也可用 add_edge",
  "graph.add_edge('node_a', 'node_b')",
  "graph.add_edge('node_b', END)",
  '',
  '# 4. 编译图',
  'app = graph.compile()',
  '',
  '# 5. 执行图',
  "result = app.invoke({'text': '输入文本'})",
  "print(result)  # {'text': '...', 'step': 'B'}",
].join('\n')

export const stage2JsCode = [
  "import { StateGraph, Annotation, START, END } from '@langchain/langgraph'",
  "import { messagesStateReducer } from '@langchain/langgraph'",
  '',
  '// ============================================================',
  '// 阶段二核心：Annotation 状态定义 — 三种 Reducer 类型',
  '// ============================================================',
  '',
  '// 1. 定义状态（使用 Annotation.Root + 三种 reducer）',
  'const stateDefinition = Annotation.Root({',
  '  // ① 带 reducer 的状态键：追加消息列表',
  '  //    官网推荐使用 messagesStateReducer（支持 RemoveMessage、ID 去重）',
  '  messages: Annotation<string[]>({',
  '    reducer: (left, right) => left.concat(right),',
  '    default: () => [],',
  '  }),',
  '  // ② 带 reducer 的状态键：累加计数器',
  '  counter: Annotation<number>({',
  '    reducer: (left, right) => left + right,',
  '    default: () => 0,',
  '  }),',
  '  // ③ 简单状态键：LastValue（默认覆盖）',
  '  //    Annotation<string>() 等价于 Annotation<string>({})',
  '  currentStep: Annotation<string>({',
  "    default: () => '未开始',",
  '  }),',
  '})',
  '',
  '// 2. 类型推导（AnnotationRoot 内置 .State / .Update / .Node）',
  'type State = typeof stateDefinition.State',
  '  → { messages: string[], counter: number, currentStep: string }',
  'type Update = typeof stateDefinition.Update',
  '  → Partial<State>（所有字段可选）',
  'type NodeFn = typeof stateDefinition.Node',
  '  → (state: State) => Update | Partial<State>',
  '',
  '// 3. 定义节点函数（返回 Partial<State>）',
  'const nodeA = (state) => ({',
  '  messages: [`[A] ${new Date().toLocaleTimeString()} 收到: ${state.input}`],',
  '  counter: 1,          // 累加：当前值 + 1',
  "  currentStep: 'nodeA', // 覆盖：直接替换",
  '})',
  '',
  'const nodeB = (state) => ({',
  '  messages: [`[B] 处理完成，共 ${state.messages.length + 1} 条消息`],',
  '  counter: 1,          // 累加：当前值 + 1',
  "  currentStep: 'nodeB', // 覆盖：直接替换",
  '})',
  '',
  '// 4. 构建图',
  'const graph = new StateGraph(stateDefinition)',
  "  .addNode('nodeA', nodeA)",
  "  .addNode('nodeB', nodeB)",
  "  .addEdge(START, 'nodeA')",
  "  .addEdge('nodeA', 'nodeB')",
  "  .addEdge('nodeB', END)",
  '',
  '// 5. 编译并执行',
  'const app = graph.compile()',
  "const result = await app.invoke({ input: 'Hello' })",
  "result.messages: ['[A] ...', '[B] ...']  ← 两条消息都被保留",
  'result.counter: 2                          ← 1 + 1 = 2（累加）',
  "result.currentStep: 'nodeB'                ← 被 nodeB 覆盖",
  '',
  '// ============================================================',
  '// 补充：使用 MessagesAnnotation 预构建状态（官网推荐方式）',
  '// ============================================================',
  'import { MessagesAnnotation, StateGraph } from "@langchain/langgraph"',
  'MessagesAnnotation 内部等价于：',
  'Annotation.Root({',
  '  messages: Annotation<BaseMessage[]>({',
  '     reducer: messagesStateReducer,  // 支持 RemoveMessage、ID 去重',
  '     default: () => [],',
  '   }),',
  ' })',
  '',
  'const graph = new StateGraph(MessagesAnnotation)',
  '   .addNode(...)',
  '   .compile()',
].join('\n')

export const stage2PyCode = [
  'from typing import TypedDict, Annotated',
  'import operator',
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.graph import MessagesState  # 预构建消息状态',
  '',
  '# ============================================================',
  '# Python 版：使用 TypedDict + Annotated 定义状态',
  '# ============================================================',
  '',
  '# 1. 定义状态（Python 版：用 TypedDict + Annotated）',
  'class State(TypedDict):',
  '    # ① 追加消息列表（operator.add 等同于 list concatenation）',
  '    messages: Annotated[list[str], operator.add]',
  '    # ② 累加计数器',
  '    counter: Annotated[int, operator.add]',
  '    # ③ 简单覆盖（默认行为，无需 Annotated）',
  '    current_step: str',
  '',
  '# 2. 定义节点函数（返回 dict）',
  'def node_a(state: State) -> dict:',
  '    return {',
  "        'messages': ['[A] 收到消息'],",
  "        'counter': 1,          # 累加",
  "        'current_step': 'nodeA' # 覆盖",
  '    }',
  '',
  'def node_b(state: State) -> dict:',
  '    return {',
  "        'messages': ['[B] 处理完成'],",
  "        'counter': 1,          # 累加",
  "        'current_step': 'nodeB' # 覆盖",
  '    }',
  '',
  '# 3. 构建图',
  'graph = StateGraph(State)',
  "graph.add_node('nodeA', node_a)",
  "graph.add_node('nodeB', node_b)",
  "graph.add_edge(START, 'nodeA')",
  "graph.add_edge('nodeA', 'nodeB')",
  "graph.add_edge('nodeB', END)",
  '',
  '# 4. 编译并执行',
  'app = graph.compile()',
  "result = app.invoke({'messages': [], 'counter': 0, 'current_step': ''})",
  "# result['messages']: ['[A] ...', '[B] ...']",
  "# result['counter']: 2",
  "# result['current_step']: 'nodeB'",
  '',
  '',
  '# ============================================================',
  '# 补充：使用 MessagesState 预构建状态（Python 版推荐方式）',
  '# ============================================================',
  '# from langgraph.graph import MessagesState',
  '#',
  '# # MessagesState 内部等价于：',
  '# # class MessagesState(TypedDict):',
  '# #     messages: Annotated[list[BaseMessage], add_messages]',
  '#',
  '# graph = StateGraph(MessagesState)',
  '# graph.add_node(...)',
  '# app = graph.compile()',
].join('\n')

export const stage3JsCode = [
  "import { StateGraph, Annotation, START, END } from '@langchain/langgraph'",
  "import { ToolNode, toolsCondition } from '@langchain/langgraph/prebuilt'",
  "import { ChatOpenAI } from '@langchain/openai'",
  "import { tool } from '@langchain/core/tools'",
  "import { z } from 'zod'",
  '',
  '// 1. 定义工具',
  'const getWeather = tool(async ({ city }) => {',
  "  return `${city}天气：晴，25°C`",
  '}, {',
  "  name: 'get_weather',",
  "  description: '查询城市天气'",
  '  schema: z.object({ city: z.string() })',
  '})',
  '',
  '// 2. 定义状态',
  'const AgentState = Annotation.Root({',
  '  messages: Annotation<BaseMessage[]>({',
  '    reducer: (left, right) => left.concat(right),',
  '    default: () => [],',
  '  }),',
  '})',
  '',
  '// 3. 创建 LLM 并绑定工具',
  "const llm = new ChatOpenAI({ model: '...' })",
  'const llmWithTools = llm.bindTools(tools)',
  '',
  '// 4. agent 节点：调用 LLM',
  'const callModel = async (state) => {',
  '  const response = await llmWithTools.invoke(state.messages)',
  '  return { messages: [response] }',
  '}',
  '',
  '// 5. 构建图',
  '',
  '// ===== 方式一：toolsCondition（推荐） =====',
  'const graph1 = new StateGraph(AgentState)',
  "  .addNode('agent', callModel)",
  "  .addNode('tools', new ToolNode(tools))",
  "  .addEdge(START, 'agent')",
  "  .addConditionalEdges('agent', toolsCondition)",
  "  .addEdge('tools', 'agent')",
  '',
  '// ===== 方式二：自定义 router =====',
  'const graph2 = new StateGraph(AgentState)',
  "  .addNode('agent', callModel)",
  "  .addNode('tools', new ToolNode(tools))",
  "  .addEdge(START, 'agent')",
  "  .addConditionalEdges('agent', (state) => {",
  '    const lastMsg = state.messages[state.messages.length - 1]',
  "    if (lastMsg.tool_calls?.length > 0) return 'tools'",
  '    return END',
  '  })',
  "  .addEdge('tools', 'agent')",
  '',
  '// 6. 编译并执行',
  'const app = graph1.compile()',
  "const result = await app.invoke({ messages: [new HumanMessage('北京天气')] })",
].join('\n')

export const stage3PyCode = [
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.graph import MessagesState',
  'from langgraph.prebuilt import ToolNode, tools_condition',
  'from langchain_openai import ChatOpenAI',
  '',
  '# 1. 定义工具',
  'def get_weather(city: str) -> str:',
  "    return f'{city}天气：晴，25°C'",
  '',
  '# 2. 创建 LLM 并绑定工具',
  "llm = ChatOpenAI(model='...')",
  'llm_with_tools = llm.bind_tools(tools)',
  '',
  '# 3. agent 节点',
  'def call_model(state: MessagesState) -> dict:',
  '    response = llm_with_tools.invoke(state["messages"])',
  "    return {'messages': [response]}",
  '',
  '# 4. 构建图',
  '',
  '# ===== 方式一：tools_condition（推荐） =====',
  'graph1 = StateGraph(MessagesState)',
  "graph1.add_node('agent', call_model)",
  "graph1.add_node('tools', ToolNode(tools))",
  "graph1.add_edge(START, 'agent')",
  "graph1.add_conditional_edges('agent', tools_condition)",
  "graph1.add_edge('tools', 'agent')",
  '',
  '# ===== 方式二：自定义 router =====',
  'def custom_router(state: MessagesState) -> str:',
  "    last_msg = state['messages'][-1]",
  "    if hasattr(last_msg, 'tool_calls') and last_msg.tool_calls:",
  "        return 'tools'",
  '    return END',
  '',
  'graph2 = StateGraph(MessagesState)',
  "graph2.add_node('agent', call_model)",
  "graph2.add_node('tools', ToolNode(tools))",
  "graph2.add_edge(START, 'agent')",
  "graph2.add_conditional_edges('agent', custom_router)",
  "graph2.add_edge('tools', 'agent')",
  '',
  '# 5. 编译并执行',
  'app = graph1.compile()',
  "result = app.invoke({'messages': [HumanMessage(content='北京天气')]})",
].join('\n')

export const stage4JsCode = [
  "import { StateGraph, Annotation, START, END, Command } from '@langchain/langgraph'",
  "import { ChatOpenAI } from '@langchain/openai'",
  '',
  '// ============================================================',
  '// 方式一：Command 命令式路由（节点内决策）',
  '// ============================================================',
  '',
  '// 1. 定义状态',
  'const AnalyzerState = Annotation.Root({',
  '  text: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => ''",
  '  }),',
  '  priority: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => 'normal'",
  '  }),',
  '  handled: Annotation<boolean>({',
  '    reducer: (_, right) => right,',
  '    default: () => false',
  '  }),',
  '  handlerNote: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => ''",
  '  }),',
  '})',
  '',
  '// 2. analyzer 节点：LLM 分析 + Command 动态路由',
  'const analyzerNode = async (state) => {',
  '  const { text } = state',
  '',
  '  // ⚡ 用 LLM 分析消息分类',
  "  const prompt = `请分析以下消息的分类，只返回一个单词：",
  "  - 紧急/故障/宕机 → 返回 'urgent'",
  "  - 投诉/不满/抱怨 → 返回 'complaint'",
  "  - 结束/终止/再见 → 返回 'end'",
  "  - 其他 → 返回 'normal'",
  '',
  "  消息：${text}",
  '',
  '  分类结果：`',
  '',
  '  const response = await llm.invoke([new HumanMessage(prompt)])',
  "  const category = response.content.trim().toLowerCase()",
  '',
  '  // 🔀 在节点内部根据 LLM 分类结果用 Command 动态路由',
  "  if (category === 'urgent') {",
  '    return new Command({',
  "      goto: 'priorityHandler',",
  "      update: { priority: 'high', handled: true },",
  '    })',
  "  } else if (category === 'complaint') {",
  '    return new Command({',
  "      goto: 'escalationHandler',",
  "      update: { priority: 'critical', handled: true },",
  '    })',
  "  } else if (category === 'end') {",
  '    return new Command({',
  '      goto: END,',
  '      update: { handled: true },',
  '    })',
  '  }',
  '',
  '  // ➡️ 普通消息 → 不返回 Command，走默认边',
  "  return { priority: 'normal', handled: false }",
  '}',
  '',
  '// 3. 各处理节点',
  "const priorityHandler = (state) => ({",
  "  handlerNote: `[优先处理] 已紧急响应: ${state.text.substring(0, 50)}`,",
  '})',
  '',
  "const escalationHandler = (state) => ({",
  "  handlerNote: `[升级处理] 已升级投诉: ${state.text.substring(0, 50)}`,",
  '})',
  '',
  "const normalHandler = (state) => ({",
  "  handlerNote: `[普通处理] 已记录: ${state.text.substring(0, 50)}`,",
  '  handled: true,',
  '})',
  '',
  '// 4. 构建图（注意：使用 Command 的节点需要声明 ends 数组）',
  'const graph = new StateGraph(AnalyzerState)',
  "  .addNode('analyzer', analyzerNode, {",
  "    ends: ['priorityHandler', 'escalationHandler', 'normalHandler', END]",
  '  })',
  "  .addNode('priorityHandler', priorityHandler)",
  "  .addNode('escalationHandler', escalationHandler)",
  "  .addNode('normalHandler', normalHandler)",
  "  .addEdge(START, 'analyzer')",
  "  .addEdge('priorityHandler', END)",
  "  .addEdge('escalationHandler', END)",
  "  .addEdge('normalHandler', END)",
  '',
  '// 5. 编译并执行',
  'const app = graph.compile()',
  "const result = await app.invoke({ text: '紧急！服务器宕机了' })",
  '',
  '',
  '// ============================================================',
  '// 方式二：条件边 声明式路由（对比）',
  '// ============================================================',
  '',
  '// 条件边版本：同样使用 LLM 分类，仅路由方式不同',
  '// 节点只负责设置状态字段，路由逻辑在边层面的 router 函数中',
  'const analyzerNodeV2 = async (state) => {',
  '  const { text } = state',
  '',
  '  // ⚡ 用 LLM 分析消息分类（与 Command 模式相同的 prompt）',
  "  const prompt = `请分析以下消息的分类，只返回一个单词：",
  "  - 紧急/故障/宕机 → 返回 'urgent'",
  "  - 投诉/不满/抱怨 → 返回 'complaint'",
  "  - 结束/终止/再见 → 返回 'end'",
  "  - 其他 → 返回 'normal'",
  '',
  '  消息：${text}',
  '',
  '  分类结果：`',
  '',
  '  const response = await llm.invoke([new HumanMessage(prompt)])',
  "  const category = response.content.trim().toLowerCase()",
  '',
  '  // 根据 LLM 分类结果设置状态字段（不直接路由）',
  "  if (category === 'urgent') return { priority: 'high' }",
  "  if (category === 'complaint') return { priority: 'critical' }",
  "  if (category === 'end') return { shouldEnd: true }",
  "  return { priority: 'normal' }",
  '}',
  '',
  '// router 函数在边层面决策（声明式路由）',
  'const router = (state) => {',
  "  if (state.shouldEnd) return END",
  "  if (state.priority === 'high') return 'priorityHandler'",
  "  if (state.priority === 'critical') return 'escalationHandler'",
  "  return 'normalHandler'",
  '}',
  '',
  'const graphV2 = new StateGraph(AnalyzerState)',
  "  .addNode('analyzer', analyzerNodeV2)",
  "  .addNode('priorityHandler', priorityHandler)",
  "  .addNode('escalationHandler', escalationHandler)",
  "  .addNode('normalHandler', normalHandler)",
  "  .addEdge(START, 'analyzer')",
  "  .addConditionalEdges('analyzer', router)",  // ← 声明式路由',
  "  .addEdge('priorityHandler', END)",
  "  .addEdge('escalationHandler', END)",
  "  .addEdge('normalHandler', END)",
].join('\n')

export const stage4PyCode = [
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.types import Command',
  'from typing import TypedDict',
  '',
  '# ============================================================',
  '# 方式一：Command 命令式路由（节点内决策）',
  '# ============================================================',
  '',
  '# 1. 定义状态',
  'class AnalyzerState(TypedDict):',
  "    text: str",
  "    priority: str",
  "    handled: bool",
  "    handler_note: str",
  '',
  '# 2. analyzer 节点：LLM 分析 + Command 动态路由',
  'def analyzer_node(state: AnalyzerState) -> dict:',
  "    text = state.get('text', '')",
  '',
  '    # ⚡ 用 LLM 分析消息分类',
  "    prompt = f'''请分析以下消息的分类，只返回一个单词：",
  "    - 紧急/故障/宕机 → 返回 'urgent'",
  "    - 投诉/不满/抱怨 → 返回 'complaint'",
  "    - 结束/终止/再见 → 返回 'end'",
  "    - 其他 → 返回 'normal'",
  '',
  '    消息：{text}',
  '',
  "    分类结果：'''",
  '',
  '    response = llm.invoke([HumanMessage(content=prompt)])',
  '    category = response.content.strip().lower()',
  '',
  '    # 🔀 在节点内部根据 LLM 分类结果用 Command 动态路由',
  "    if category == 'urgent':",
  '        return Command(',
  "            goto='priorityHandler',",
  "            update={'priority': 'high', 'handled': True}",
  '        )',
  "    elif category == 'complaint':",
  '        return Command(',
  "            goto='escalationHandler',",
  "            update={'priority': 'critical', 'handled': True}",
  '        )',
  "    elif category == 'end':",
  '        return Command(',
  '            goto=END,',
  "            update={'handled': True}",
  '        )',
  '',
  '    # ➡️ 普通消息 → 不返回 Command，走默认边',
  "    return {'priority': 'normal', 'handled': False}",
  '',
  '# 3. 各处理节点',
  'def priority_handler(state: AnalyzerState) -> dict:',
  "    return {'handler_note': f\"[优先处理] 已紧急响应: {state['text'][:50]}\"}",
  '',
  'def escalation_handler(state: AnalyzerState) -> dict:',
  "    return {'handler_note': f\"[升级处理] 已升级投诉: {state['text'][:50]}\"}",
  '',
  'def normal_handler(state: AnalyzerState) -> dict:',
  "    return {'handler_note': f\"[普通处理] 已记录: {state['text'][:50]}\", 'handled': True}",
  '',
  '# 4. 构建图',
  'graph = StateGraph(AnalyzerState)',
  "graph.add_node('analyzer', analyzer_node)",
  "graph.add_node('priorityHandler', priority_handler)",
  "graph.add_node('escalationHandler', escalation_handler)",
  "graph.add_node('normalHandler', normal_handler)",
  "graph.add_edge(START, 'analyzer')",
  "graph.add_edge('priorityHandler', END)",
  "graph.add_edge('escalationHandler', END)",
  "graph.add_edge('normalHandler', END)",
  '',
  '# 5. 编译并执行',
  'app = graph.compile()',
  "result = app.invoke({'text': '紧急！服务器宕机了'})",
  '',
  '',
  '# ============================================================',
  '# 方式二：条件边 声明式路由（对比）',
  '# ============================================================',
  '',
  '# 条件边版本：同样使用 LLM 分类，仅路由方式不同',
  '# 节点只负责设置状态字段，路由逻辑在边层面的 router 函数中',
  'def analyzer_node_v2(state: AnalyzerState) -> dict:',
  "    text = state.get('text', '')",
  '',
  '    # ⚡ 用 LLM 分析消息分类（与 Command 模式相同的 prompt）',
  "    prompt = f'''请分析以下消息的分类，只返回一个单词：",
  "    - 紧急/故障/宕机 → 返回 'urgent'",
  "    - 投诉/不满/抱怨 → 返回 'complaint'",
  "    - 结束/终止/再见 → 返回 'end'",
  "    - 其他 → 返回 'normal'",
  '',
  '    消息：{text}',
  '',
  "    分类结果：'''",
  '',
  '    response = llm.invoke([HumanMessage(content=prompt)])',
  '    category = response.content.strip().lower()',
  '',
  '    # 根据 LLM 分类结果设置状态字段（不直接路由）',
  "    if category == 'urgent': return {'priority': 'high'}",
  "    if category == 'complaint': return {'priority': 'critical'}",
  "    if category == 'end': return {'should_end': True}",
  "    return {'priority': 'normal'}",
  '',
  'def router(state: AnalyzerState) -> str:',
  "    if state.get('should_end'): return END",
  "    if state.get('priority') == 'high': return 'priorityHandler'",
  "    if state.get('priority') == 'critical': return 'escalationHandler'",
  "    return 'normalHandler'",
  '',
  'graph_v2 = StateGraph(AnalyzerState)',
  "graph_v2.add_node('analyzer', analyzer_node_v2)",
  "graph_v2.add_node('priorityHandler', priority_handler)",
  "graph_v2.add_node('escalationHandler', escalation_handler)",
  "graph_v2.add_node('normalHandler', normal_handler)",
  "graph_v2.add_edge(START, 'analyzer')",
  "graph_v2.add_conditional_edges('analyzer', router)  # ← 声明式路由",
  "graph_v2.add_edge('priorityHandler', END)",
  "graph_v2.add_edge('escalationHandler', END)",
  "graph_v2.add_edge('normalHandler', END)",
].join('\n')

export const stage5JsCode = [
"import { StateGraph, Annotation, START, END, Command, interrupt, MemorySaver } from '@langchain/langgraph'",
  "import { ChatOpenAI } from '@langchain/openai'",
  '',
  '// ============================================================',
  '// 阶段五核心：Human-in-the-Loop — interrupt 人机协同（条件路由）',
  '// ============================================================',
  '',
  '// 1. 定义状态',
  'const ApprovalState = Annotation.Root({',
  '  plan: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => ''",
  '  }),',
  '  approved: Annotation<boolean>({',
  '    reducer: (_, right) => right,',
  '    default: () => false',
  '  }),',
  '  result: Annotation<string>({',
  '    reducer: (_, right) => right,',
  "    default: () => ''",
  '  }),',
  '})',
  '',
  '// 2. 节点1：生成方案（LLM 驱动）',
  'const generatePlan = async () => {',
  "  const plan = await llm.invoke('请生成一个执行方案...')",
  '  return { plan: plan.content }',
  '}',
  '',
  '// 3. 节点2：等待人工审批（interrupt 暂停）',
  'const waitApproval = (state) => {',
  '  // interrupt() 抛出 GraphInterrupt，暂停图执行',
  '  // 返回值是用户通过 Command({ resume }) 传入的值',
  '  const decision = interrupt({',
  "    question: '请审批以下方案：',",
  '    plan: state.plan,',
  '  })',
  '  // decision 是 resume 传入的值，如 { approved: true, comment: "..." }',
  '  return { approved: decision.approved }',
  '}',
  '',
  '// 4. 节点3：执行方案（仅批准后到达）',
  'const executePlan = () => {',
  "  return { result: '方案已执行，完成资源调配、任务分配、监控启动' }",
  '}',
  '',
  '// 5. 节点4：方案被拒后，LLM 根据反馈重新生成',
  'const revisePlan = async (state) => {',
  "  const newPlan = await llm.invoke(`根据审批意见重新生成方案...`)",
  '  // 返回新方案，重置 approved，循环回 approval 重新审批',
  '  return { plan: newPlan.content, approved: false }',
  '}',
  '',
  '// 6. 条件路由：根据审批结果决定下一步',
  'const routeAfterApproval = (state) => {',
  "  return state.approved ? 'execute' : 'revisePlan'",
  '}',
  '',
  '// 7. 构建图（条件路由 + checkpointer）',
  'const checkpointer = new MemorySaver()',
  'const graph = new StateGraph(ApprovalState)',
  "  .addNode('generate', generatePlan)",
  "  .addNode('approval', waitApproval)",
  "  .addNode('execute', executePlan)",
  "  .addNode('revisePlan', revisePlan)",
  "  .addEdge(START, 'generate')",
  "  .addEdge('generate', 'approval')",
  "  .addConditionalEdges('approval', routeAfterApproval, {",
  "    execute: 'execute',",
  "    revisePlan: 'revisePlan',",
  '  })',
  "  .addEdge('execute', END)",
  "  .addEdge('revisePlan', 'approval')  // ← 循环回 approval 重新审批",
  '',
  'const app = graph.compile({ checkpointer })  // ← 必须注入 checkpointer',
  '',
  '// 8. 第一次调用：执行到 interrupt 处暂停',
  "const threadId = 'thread-1'",
  'const result1 = await app.invoke(',
  "  { plan: '' },",
  '  { configurable: { thread_id: threadId } }',
  ')',
  '// isInterrupted(result1) === true，图暂停在 approval 节点',
  '',
  '// 9. 批准方案：恢复执行 → execute → END',
  'const result2 = await app.invoke(',
  '  new Command({ resume: { approved: true, comment: "同意执行" } }),',
  '  { configurable: { thread_id: threadId } }',
  ')',
  '// isInterrupted(result2) === false，图执行完毕 → END',
  '',
  '// 10. 拒绝方案：恢复执行 → revisePlan(LLM重新生成) → approval(再次interrupt)',
  'const result3 = await app.invoke(',
  '  new Command({ resume: { approved: false, comment: "方案不可行" } }),',
  '  { configurable: { thread_id: threadId } }',
  ')',
  '// isInterrupted(result3) === true，LLM 已重新生成方案，再次暂停等待审批',
].join('\n')

export const stage5PyCode = [
  'from typing import TypedDict',
  'from langgraph.graph import StateGraph, START, END',
  'from langgraph.types import Command, interrupt',
  'from langgraph.checkpoint.memory import MemorySaver',
  '',
  '# ============================================================',
  '# Python 版：Human-in-the-Loop — interrupt 人机协同（条件路由）',
  '# ============================================================',
  '',
  '# 1. 定义状态',
  'class ApprovalState(TypedDict):',
  '    plan: str',
  '    approved: bool',
  '    result: str',
  '',
  '# 2. 节点1：生成方案（LLM 驱动）',
  'def generate_plan(state: ApprovalState) -> dict:',
  "    plan = llm.invoke('请生成一个执行方案...')",
  "    return {'plan': plan.content}",
  '',
  '# 3. 节点2：等待人工审批（interrupt 暂停）',
  'def wait_approval(state: ApprovalState) -> dict:',
  '    decision = interrupt({',
  "        'question': '请审批以下方案：',",
  "        'plan': state['plan'],",
  '    })',
  "    return {'approved': decision['approved']}",
  '',
  '# 4. 节点3：执行方案（仅批准后到达）',
  'def execute_plan(state: ApprovalState) -> dict:',
  "    return {'result': '方案已执行，完成资源调配、任务分配、监控启动'}",
  '',
  '# 5. 节点4：方案被拒后，LLM 根据反馈重新生成',
  'def revise_plan(state: ApprovalState) -> dict:',
  "    new_plan = llm.invoke('根据审批意见重新生成方案...')",
  "    return {'plan': new_plan.content, 'approved': False}",
  '',
  '# 6. 条件路由：根据审批结果决定下一步',
  'def route_after_approval(state: ApprovalState) -> str:',
  "    return 'execute' if state['approved'] else 'revise_plan'",
  '',
  '# 7. 构建图（条件路由 + checkpointer）',
  'checkpointer = MemorySaver()',
  'graph = StateGraph(ApprovalState)',
  "graph.add_node('generate', generate_plan)",
  "graph.add_node('approval', wait_approval)",
  "graph.add_node('execute', execute_plan)",
  "graph.add_node('revise_plan', revise_plan)",
  "graph.add_edge(START, 'generate')",
  "graph.add_edge('generate', 'approval')",
  "graph.add_conditional_edges('approval', route_after_approval, {",
  "    'execute': 'execute',",
  "    'revise_plan': 'revise_plan',",
  '})',
  "graph.add_edge('execute', END)",
  "graph.add_edge('revise_plan', 'approval')  # ← 循环回 approval 重新审批",
  '',
  'app = graph.compile(checkpointer=checkpointer)',
  '',
  '# 8. 第一次调用：停在 approval 节点',
  "thread_id = 'thread-1'",
  'result1 = app.invoke(',
  "    {'plan': ''},",
  "    {'configurable': {'thread_id': thread_id}}",
  ')',
  '# result1 包含 __interrupt__，图暂停在 approval 节点',
  '',
  '# 9. 批准方案：恢复执行 → execute → END',
  'result2 = app.invoke(',
  "    Command(resume={'approved': True, 'comment': '同意执行'}),",
  "    {'configurable': {'thread_id': thread_id}}",
  ')',
  '# result2 不包含 __interrupt__，图执行完毕 → END',
  '',
  '# 10. 拒绝方案：恢复执行 → revise_plan(LLM重新生成) → approval(再次interrupt)',
  'result3 = app.invoke(',
  "    Command(resume={'approved': False, 'comment': '方案不可行'}),",
  "    {'configurable': {'thread_id': thread_id}}",
  ')',
  '# result3 包含 __interrupt__，LLM 已重新生成方案，再次暂停等待审批',
].join('\n')
